package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Aaa generated by hbm2java
 */
@Entity
@Table(name = "aaa", catalog = "ptutors_db")
public class Aaa implements java.io.Serializable {

	private int id;
	private String name;

	public Aaa() {
	}

	public Aaa(int id) {
		this.id = id;
	}

	public Aaa(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getid() {
		return this.id;
	}

	public void setid(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
