package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AcademicNewsletter generated by hbm2java
 */
@Entity
@Table(name = "academic_newsletter", catalog = "ptutors_db")
public class AcademicNewsletter implements java.io.Serializable {

	private AcademicNewsletterId id;

	public AcademicNewsletter() {
	}

	public AcademicNewsletter(AcademicNewsletterId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "title", column = @Column(name = "TITLE", length = 200)),
			@AttributeOverride(name = "date", column = @Column(name = "DATE", length = 10)),
			@AttributeOverride(name = "description", column = @Column(name = "DESCRIPTION", length = 500)),
			@AttributeOverride(name = "websiteUrl", column = @Column(name = "WEBSITE_URL", length = 100)) })
	public AcademicNewsletterId getId() {
		return this.id;
	}

	public void setId(AcademicNewsletterId id) {
		this.id = id;
	}

}
