package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AcademicNewsletterId generated by hbm2java
 */
@Embeddable
public class AcademicNewsletterId implements java.io.Serializable {

	private String title;
	private Date date;
	private String description;
	private String websiteUrl;

	public AcademicNewsletterId() {
	}

	public AcademicNewsletterId(String title, Date date, String description, String websiteUrl) {
		this.title = title;
		this.date = date;
		this.description = description;
		this.websiteUrl = websiteUrl;
	}

	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DATE", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "WEBSITE_URL", length = 100)
	public String getWebsiteUrl() {
		return this.websiteUrl;
	}

	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcademicNewsletterId))
			return false;
		AcademicNewsletterId castOther = (AcademicNewsletterId) other;

		return ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null && castOther.getTitle() != null
				&& this.getTitle().equals(castOther.getTitle())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getWebsiteUrl() == castOther.getWebsiteUrl())
						|| (this.getWebsiteUrl() != null && castOther.getWebsiteUrl() != null
								&& this.getWebsiteUrl().equals(castOther.getWebsiteUrl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getWebsiteUrl() == null ? 0 : this.getWebsiteUrl().hashCode());
		return result;
	}

}
