package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Assistance generated by hbm2java
 */
@Entity
@Table(name = "assistance", catalog = "ptutors_db")
public class Assistance implements java.io.Serializable {

	private Integer assistanceId;
	private String name;
	private String contactNumber;
	private String emailAddress;
	private String locationName;
	private String countryName;
	private String address;
	private String description;
	private Date postingDate;
	private String replyStatus;

	public Assistance() {
	}

	public Assistance(String name, String contactNumber, String emailAddress, String locationName, String countryName,
			String address, String description, Date postingDate, String replyStatus) {
		this.name = name;
		this.contactNumber = contactNumber;
		this.emailAddress = emailAddress;
		this.locationName = locationName;
		this.countryName = countryName;
		this.address = address;
		this.description = description;
		this.postingDate = postingDate;
		this.replyStatus = replyStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ASSISTANCE_ID", unique = true, nullable = false)
	public Integer getAssistanceId() {
		return this.assistanceId;
	}

	public void setAssistanceId(Integer assistanceId) {
		this.assistanceId = assistanceId;
	}

	@Column(name = "NAME", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CONTACT_NUMBER", length = 200)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "EMAIL_ADDRESS", length = 100)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "LOCATION_NAME", length = 200)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "COUNTRY_NAME", length = 200)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "ADDRESS", length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "POSTING_DATE", length = 10)
	public Date getPostingDate() {
		return this.postingDate;
	}

	public void setPostingDate(Date postingDate) {
		this.postingDate = postingDate;
	}

	@Column(name = "REPLY_STATUS", length = 100)
	public String getReplyStatus() {
		return this.replyStatus;
	}

	public void setReplyStatus(String replyStatus) {
		this.replyStatus = replyStatus;
	}

}
