package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CandidateCoursePayment generated by hbm2java
 */
@Entity
@Table(name = "candidate_course_payment", catalog = "ptutors_db")
public class CandidateCoursePayment implements java.io.Serializable {

	private Integer applicationId;
	private String applicantEmail;
	private String subjectName;
	private String receiveStatus;
	private String paymentMode;

	public CandidateCoursePayment() {
	}

	public CandidateCoursePayment(String applicantEmail, String subjectName, String receiveStatus, String paymentMode) {
		this.applicantEmail = applicantEmail;
		this.subjectName = subjectName;
		this.receiveStatus = receiveStatus;
		this.paymentMode = paymentMode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "application_id", unique = true, nullable = false)
	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "applicant_email", nullable = false, length = 50)
	public String getApplicantEmail() {
		return this.applicantEmail;
	}

	public void setApplicantEmail(String applicantEmail) {
		this.applicantEmail = applicantEmail;
	}

	@Column(name = "subject_name", nullable = false, length = 50)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@Column(name = "receive_status", nullable = false, length = 50)
	public String getReceiveStatus() {
		return this.receiveStatus;
	}

	public void setReceiveStatus(String receiveStatus) {
		this.receiveStatus = receiveStatus;
	}

	@Column(name = "payment_mode", nullable = false, length = 50)
	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

}
