package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CareerQuestionAnswersId generated by hbm2java
 */
@Embeddable
public class CareerQuestionAnswersId implements java.io.Serializable {

	private Integer careerQuestionId;
	private String careerQuestionAnswer;
	private Integer careerQuestionRepliedBy;
	private Date careerQuestionRepliedTime;

	public CareerQuestionAnswersId() {
	}

	public CareerQuestionAnswersId(Integer careerQuestionId, String careerQuestionAnswer,
			Integer careerQuestionRepliedBy, Date careerQuestionRepliedTime) {
		this.careerQuestionId = careerQuestionId;
		this.careerQuestionAnswer = careerQuestionAnswer;
		this.careerQuestionRepliedBy = careerQuestionRepliedBy;
		this.careerQuestionRepliedTime = careerQuestionRepliedTime;
	}

	@Column(name = "career_question_id")
	public Integer getCareerQuestionId() {
		return this.careerQuestionId;
	}

	public void setCareerQuestionId(Integer careerQuestionId) {
		this.careerQuestionId = careerQuestionId;
	}

	@Column(name = "career_question_answer", length = 500)
	public String getCareerQuestionAnswer() {
		return this.careerQuestionAnswer;
	}

	public void setCareerQuestionAnswer(String careerQuestionAnswer) {
		this.careerQuestionAnswer = careerQuestionAnswer;
	}

	@Column(name = "career_question_replied_by")
	public Integer getCareerQuestionRepliedBy() {
		return this.careerQuestionRepliedBy;
	}

	public void setCareerQuestionRepliedBy(Integer careerQuestionRepliedBy) {
		this.careerQuestionRepliedBy = careerQuestionRepliedBy;
	}

	@Column(name = "career_question_replied_time", length = 19)
	public Date getCareerQuestionRepliedTime() {
		return this.careerQuestionRepliedTime;
	}

	public void setCareerQuestionRepliedTime(Date careerQuestionRepliedTime) {
		this.careerQuestionRepliedTime = careerQuestionRepliedTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CareerQuestionAnswersId))
			return false;
		CareerQuestionAnswersId castOther = (CareerQuestionAnswersId) other;

		return ((this.getCareerQuestionId() == castOther.getCareerQuestionId())
				|| (this.getCareerQuestionId() != null && castOther.getCareerQuestionId() != null
						&& this.getCareerQuestionId().equals(castOther.getCareerQuestionId())))
				&& ((this.getCareerQuestionAnswer() == castOther.getCareerQuestionAnswer())
						|| (this.getCareerQuestionAnswer() != null && castOther.getCareerQuestionAnswer() != null
								&& this.getCareerQuestionAnswer().equals(castOther.getCareerQuestionAnswer())))
				&& ((this.getCareerQuestionRepliedBy() == castOther.getCareerQuestionRepliedBy())
						|| (this.getCareerQuestionRepliedBy() != null && castOther.getCareerQuestionRepliedBy() != null
								&& this.getCareerQuestionRepliedBy().equals(castOther.getCareerQuestionRepliedBy())))
				&& ((this.getCareerQuestionRepliedTime() == castOther.getCareerQuestionRepliedTime())
						|| (this.getCareerQuestionRepliedTime() != null
								&& castOther.getCareerQuestionRepliedTime() != null
								&& this.getCareerQuestionRepliedTime()
										.equals(castOther.getCareerQuestionRepliedTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCareerQuestionId() == null ? 0 : this.getCareerQuestionId().hashCode());
		result = 37 * result + (getCareerQuestionAnswer() == null ? 0 : this.getCareerQuestionAnswer().hashCode());
		result = 37 * result
				+ (getCareerQuestionRepliedBy() == null ? 0 : this.getCareerQuestionRepliedBy().hashCode());
		result = 37 * result
				+ (getCareerQuestionRepliedTime() == null ? 0 : this.getCareerQuestionRepliedTime().hashCode());
		return result;
	}

}
