package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CareerCafe generated by hbm2java
 */
@Entity
@Table(name = "career_cafe", catalog = "ptutors_db")
public class CareerCafe implements java.io.Serializable {

	private CareerCafeId id;
	private String name;
	private String userLoginName;
	private String password;
	private Integer secretQuestionId;
	private String secretQuestionAnswer;
	private String gender;
	private Integer age;
	private String countryCode;
	private Integer locationId;
	private String area;
	private String postalCode;
	private String contactNumber;
	private Integer educationSegmentId;
	private Date registrationDate;
	private Boolean profileVerificationStatus;
	private Boolean profileActiveDeactiveStatus;

	public CareerCafe() {
	}

	public CareerCafe(CareerCafeId id) {
		this.id = id;
	}

	public CareerCafe(CareerCafeId id, String name, String userLoginName, String password, Integer secretQuestionId,
			String secretQuestionAnswer, String gender, Integer age, String countryCode, Integer locationId,
			String area, String postalCode, String contactNumber, Integer educationSegmentId, Date registrationDate,
			Boolean profileVerificationStatus, Boolean profileActiveDeactiveStatus) {
		this.id = id;
		this.name = name;
		this.userLoginName = userLoginName;
		this.password = password;
		this.secretQuestionId = secretQuestionId;
		this.secretQuestionAnswer = secretQuestionAnswer;
		this.gender = gender;
		this.age = age;
		this.countryCode = countryCode;
		this.locationId = locationId;
		this.area = area;
		this.postalCode = postalCode;
		this.contactNumber = contactNumber;
		this.educationSegmentId = educationSegmentId;
		this.registrationDate = registrationDate;
		this.profileVerificationStatus = profileVerificationStatus;
		this.profileActiveDeactiveStatus = profileActiveDeactiveStatus;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "memberId", column = @Column(name = "member_id", nullable = false)),
			@AttributeOverride(name = "emailAddress", column = @Column(name = "email_address", nullable = false, length = 200)) })
	public CareerCafeId getId() {
		return this.id;
	}

	public void setId(CareerCafeId id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "user_login_name", length = 200)
	public String getUserLoginName() {
		return this.userLoginName;
	}

	public void setUserLoginName(String userLoginName) {
		this.userLoginName = userLoginName;
	}

	@Column(name = "password", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "secret_question_id")
	public Integer getSecretQuestionId() {
		return this.secretQuestionId;
	}

	public void setSecretQuestionId(Integer secretQuestionId) {
		this.secretQuestionId = secretQuestionId;
	}

	@Column(name = "secret_question_answer", length = 200)
	public String getSecretQuestionAnswer() {
		return this.secretQuestionAnswer;
	}

	public void setSecretQuestionAnswer(String secretQuestionAnswer) {
		this.secretQuestionAnswer = secretQuestionAnswer;
	}

	@Column(name = "gender", length = 6)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "country_code", length = 4)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "location_id")
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	@Column(name = "area", length = 200)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "postal_code", length = 50)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "contact_number", length = 200)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "education_segment_id")
	public Integer getEducationSegmentId() {
		return this.educationSegmentId;
	}

	public void setEducationSegmentId(Integer educationSegmentId) {
		this.educationSegmentId = educationSegmentId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "registration_date", length = 10)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "profile_verification_status")
	public Boolean getProfileVerificationStatus() {
		return this.profileVerificationStatus;
	}

	public void setProfileVerificationStatus(Boolean profileVerificationStatus) {
		this.profileVerificationStatus = profileVerificationStatus;
	}

	@Column(name = "profile_active_deactive_status")
	public Boolean getProfileActiveDeactiveStatus() {
		return this.profileActiveDeactiveStatus;
	}

	public void setProfileActiveDeactiveStatus(Boolean profileActiveDeactiveStatus) {
		this.profileActiveDeactiveStatus = profileActiveDeactiveStatus;
	}

}
