package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CareerCafeId generated by hbm2java
 */
@Embeddable
public class CareerCafeId implements java.io.Serializable {

	private int memberId;
	private String emailAddress;

	public CareerCafeId() {
	}

	public CareerCafeId(int memberId, String emailAddress) {
		this.memberId = memberId;
		this.emailAddress = emailAddress;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "email_address", nullable = false, length = 200)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CareerCafeId))
			return false;
		CareerCafeId castOther = (CareerCafeId) other;

		return (this.getMemberId() == castOther.getMemberId())
				&& ((this.getEmailAddress() == castOther.getEmailAddress())
						|| (this.getEmailAddress() != null && castOther.getEmailAddress() != null
								&& this.getEmailAddress().equals(castOther.getEmailAddress())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemberId();
		result = 37 * result + (getEmailAddress() == null ? 0 : this.getEmailAddress().hashCode());
		return result;
	}

}
