package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CcaStudentLanguageId generated by hbm2java
 */
@Embeddable
public class CcaStudentLanguageId implements java.io.Serializable {

	private Integer studentId;
	private String language;
	private String status;

	public CcaStudentLanguageId() {
	}

	public CcaStudentLanguageId(Integer studentId, String language, String status) {
		this.studentId = studentId;
		this.language = language;
		this.status = status;
	}

	@Column(name = "student_id")
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@Column(name = "language", length = 20)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CcaStudentLanguageId))
			return false;
		CcaStudentLanguageId castOther = (CcaStudentLanguageId) other;

		return ((this.getStudentId() == castOther.getStudentId()) || (this.getStudentId() != null
				&& castOther.getStudentId() != null && this.getStudentId().equals(castOther.getStudentId())))
				&& ((this.getLanguage() == castOther.getLanguage()) || (this.getLanguage() != null
						&& castOther.getLanguage() != null && this.getLanguage().equals(castOther.getLanguage())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStudentId() == null ? 0 : this.getStudentId().hashCode());
		result = 37 * result + (getLanguage() == null ? 0 : this.getLanguage().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
