package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CcaStudentLanguage generated by hbm2java
 */
@Entity
@Table(name = "cca_student_language", catalog = "ptutors_db")
public class CcaStudentLanguage implements java.io.Serializable {

	private CcaStudentLanguageId id;
	private CcaStudent ccaStudent;

	public CcaStudentLanguage() {
	}

	public CcaStudentLanguage(CcaStudentLanguageId id) {
		this.id = id;
	}

	public CcaStudentLanguage(CcaStudentLanguageId id, CcaStudent ccaStudent) {
		this.id = id;
		this.ccaStudent = ccaStudent;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "studentId", column = @Column(name = "student_id")),
			@AttributeOverride(name = "language", column = @Column(name = "language", length = 20)),
			@AttributeOverride(name = "status", column = @Column(name = "status", length = 10)) })
	public CcaStudentLanguageId getId() {
		return this.id;
	}

	public void setId(CcaStudentLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", insertable = false, updatable = false)
	public CcaStudent getCcaStudent() {
		return this.ccaStudent;
	}

	public void setCcaStudent(CcaStudent ccaStudent) {
		this.ccaStudent = ccaStudent;
	}

}
