package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CcaTutorLanguageId generated by hbm2java
 */
@Embeddable
public class CcaTutorLanguageId implements java.io.Serializable {

	private Integer tutorId;
	private String language;
	private String status;

	public CcaTutorLanguageId() {
	}

	public CcaTutorLanguageId(Integer tutorId, String language, String status) {
		this.tutorId = tutorId;
		this.language = language;
		this.status = status;
	}

	@Column(name = "tutor_id")
	public Integer getTutorId() {
		return this.tutorId;
	}

	public void setTutorId(Integer tutorId) {
		this.tutorId = tutorId;
	}

	@Column(name = "language", length = 20)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CcaTutorLanguageId))
			return false;
		CcaTutorLanguageId castOther = (CcaTutorLanguageId) other;

		return ((this.getTutorId() == castOther.getTutorId()) || (this.getTutorId() != null
				&& castOther.getTutorId() != null && this.getTutorId().equals(castOther.getTutorId())))
				&& ((this.getLanguage() == castOther.getLanguage()) || (this.getLanguage() != null
						&& castOther.getLanguage() != null && this.getLanguage().equals(castOther.getLanguage())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTutorId() == null ? 0 : this.getTutorId().hashCode());
		result = 37 * result + (getLanguage() == null ? 0 : this.getLanguage().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
