package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CompanyType generated by hbm2java
 */
@Entity
@Table(name = "company_type", catalog = "ptutors_db")
public class CompanyType implements java.io.Serializable {

	private Integer companyNameId;
	private String companyNameType;

	public CompanyType() {
	}

	public CompanyType(String companyNameType) {
		this.companyNameType = companyNameType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "company_name_id", unique = true, nullable = false)
	public Integer getCompanyNameId() {
		return this.companyNameId;
	}

	public void setCompanyNameId(Integer companyNameId) {
		this.companyNameId = companyNameId;
	}

	@Column(name = "company_name_type", length = 100)
	public String getCompanyNameType() {
		return this.companyNameType;
	}

	public void setCompanyNameType(String companyNameType) {
		this.companyNameType = companyNameType;
	}

}
