package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContactUs generated by hbm2java
 */
@Entity
@Table(name = "contact_us", catalog = "ptutors_db")
public class ContactUs implements java.io.Serializable {

	private ContactUsId id;

	public ContactUs() {
	}

	public ContactUs(ContactUsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "contactAddressTitleName", column = @Column(name = "CONTACT_ADDRESS_TITLE_NAME", length = 200)),
			@AttributeOverride(name = "contactAddressStreetName", column = @Column(name = "CONTACT_ADDRESS_STREET_NAME", length = 200)),
			@AttributeOverride(name = "contactAddressAreaName", column = @Column(name = "CONTACT_ADDRESS_AREA_NAME", length = 200)),
			@AttributeOverride(name = "contactAddressLocationName", column = @Column(name = "CONTACT_ADDRESS_LOCATION_NAME", length = 200)),
			@AttributeOverride(name = "contactAddressStateName", column = @Column(name = "CONTACT_ADDRESS_STATE_NAME", length = 200)),
			@AttributeOverride(name = "contactAddressCountryName", column = @Column(name = "CONTACT_ADDRESS_COUNTRY_NAME", length = 200)),
			@AttributeOverride(name = "contactAddressPhoneNo", column = @Column(name = "CONTACT_ADDRESS_PHONE_NO", length = 200)),
			@AttributeOverride(name = "contactAddressMobileNo", column = @Column(name = "CONTACT_ADDRESS_MOBILE_NO", length = 200)),
			@AttributeOverride(name = "contactAddressFaxNo", column = @Column(name = "CONTACT_ADDRESS_FAX_NO", length = 200)),
			@AttributeOverride(name = "contactAddressEmailId", column = @Column(name = "CONTACT_ADDRESS_EMAIL_ID", length = 200)) })
	public ContactUsId getId() {
		return this.id;
	}

	public void setId(ContactUsId id) {
		this.id = id;
	}

}
