package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContactUsId generated by hbm2java
 */
@Embeddable
public class ContactUsId implements java.io.Serializable {

	private String contactAddressTitleName;
	private String contactAddressStreetName;
	private String contactAddressAreaName;
	private String contactAddressLocationName;
	private String contactAddressStateName;
	private String contactAddressCountryName;
	private String contactAddressPhoneNo;
	private String contactAddressMobileNo;
	private String contactAddressFaxNo;
	private String contactAddressEmailId;

	public ContactUsId() {
	}

	public ContactUsId(String contactAddressTitleName, String contactAddressStreetName, String contactAddressAreaName,
			String contactAddressLocationName, String contactAddressStateName, String contactAddressCountryName,
			String contactAddressPhoneNo, String contactAddressMobileNo, String contactAddressFaxNo,
			String contactAddressEmailId) {
		this.contactAddressTitleName = contactAddressTitleName;
		this.contactAddressStreetName = contactAddressStreetName;
		this.contactAddressAreaName = contactAddressAreaName;
		this.contactAddressLocationName = contactAddressLocationName;
		this.contactAddressStateName = contactAddressStateName;
		this.contactAddressCountryName = contactAddressCountryName;
		this.contactAddressPhoneNo = contactAddressPhoneNo;
		this.contactAddressMobileNo = contactAddressMobileNo;
		this.contactAddressFaxNo = contactAddressFaxNo;
		this.contactAddressEmailId = contactAddressEmailId;
	}

	@Column(name = "CONTACT_ADDRESS_TITLE_NAME", length = 200)
	public String getContactAddressTitleName() {
		return this.contactAddressTitleName;
	}

	public void setContactAddressTitleName(String contactAddressTitleName) {
		this.contactAddressTitleName = contactAddressTitleName;
	}

	@Column(name = "CONTACT_ADDRESS_STREET_NAME", length = 200)
	public String getContactAddressStreetName() {
		return this.contactAddressStreetName;
	}

	public void setContactAddressStreetName(String contactAddressStreetName) {
		this.contactAddressStreetName = contactAddressStreetName;
	}

	@Column(name = "CONTACT_ADDRESS_AREA_NAME", length = 200)
	public String getContactAddressAreaName() {
		return this.contactAddressAreaName;
	}

	public void setContactAddressAreaName(String contactAddressAreaName) {
		this.contactAddressAreaName = contactAddressAreaName;
	}

	@Column(name = "CONTACT_ADDRESS_LOCATION_NAME", length = 200)
	public String getContactAddressLocationName() {
		return this.contactAddressLocationName;
	}

	public void setContactAddressLocationName(String contactAddressLocationName) {
		this.contactAddressLocationName = contactAddressLocationName;
	}

	@Column(name = "CONTACT_ADDRESS_STATE_NAME", length = 200)
	public String getContactAddressStateName() {
		return this.contactAddressStateName;
	}

	public void setContactAddressStateName(String contactAddressStateName) {
		this.contactAddressStateName = contactAddressStateName;
	}

	@Column(name = "CONTACT_ADDRESS_COUNTRY_NAME", length = 200)
	public String getContactAddressCountryName() {
		return this.contactAddressCountryName;
	}

	public void setContactAddressCountryName(String contactAddressCountryName) {
		this.contactAddressCountryName = contactAddressCountryName;
	}

	@Column(name = "CONTACT_ADDRESS_PHONE_NO", length = 200)
	public String getContactAddressPhoneNo() {
		return this.contactAddressPhoneNo;
	}

	public void setContactAddressPhoneNo(String contactAddressPhoneNo) {
		this.contactAddressPhoneNo = contactAddressPhoneNo;
	}

	@Column(name = "CONTACT_ADDRESS_MOBILE_NO", length = 200)
	public String getContactAddressMobileNo() {
		return this.contactAddressMobileNo;
	}

	public void setContactAddressMobileNo(String contactAddressMobileNo) {
		this.contactAddressMobileNo = contactAddressMobileNo;
	}

	@Column(name = "CONTACT_ADDRESS_FAX_NO", length = 200)
	public String getContactAddressFaxNo() {
		return this.contactAddressFaxNo;
	}

	public void setContactAddressFaxNo(String contactAddressFaxNo) {
		this.contactAddressFaxNo = contactAddressFaxNo;
	}

	@Column(name = "CONTACT_ADDRESS_EMAIL_ID", length = 200)
	public String getContactAddressEmailId() {
		return this.contactAddressEmailId;
	}

	public void setContactAddressEmailId(String contactAddressEmailId) {
		this.contactAddressEmailId = contactAddressEmailId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactUsId))
			return false;
		ContactUsId castOther = (ContactUsId) other;

		return ((this.getContactAddressTitleName() == castOther.getContactAddressTitleName())
				|| (this.getContactAddressTitleName() != null && castOther.getContactAddressTitleName() != null
						&& this.getContactAddressTitleName().equals(castOther.getContactAddressTitleName())))
				&& ((this.getContactAddressStreetName() == castOther.getContactAddressStreetName())
						|| (this.getContactAddressStreetName() != null
								&& castOther.getContactAddressStreetName() != null
								&& this.getContactAddressStreetName().equals(castOther.getContactAddressStreetName())))
				&& ((this.getContactAddressAreaName() == castOther.getContactAddressAreaName())
						|| (this.getContactAddressAreaName() != null && castOther.getContactAddressAreaName() != null
								&& this.getContactAddressAreaName().equals(castOther.getContactAddressAreaName())))
				&& ((this.getContactAddressLocationName() == castOther.getContactAddressLocationName())
						|| (this.getContactAddressLocationName() != null
								&& castOther.getContactAddressLocationName() != null
								&& this.getContactAddressLocationName()
										.equals(castOther.getContactAddressLocationName())))
				&& ((this.getContactAddressStateName() == castOther.getContactAddressStateName())
						|| (this.getContactAddressStateName() != null && castOther.getContactAddressStateName() != null
								&& this.getContactAddressStateName().equals(castOther.getContactAddressStateName())))
				&& ((this.getContactAddressCountryName() == castOther.getContactAddressCountryName())
						|| (this.getContactAddressCountryName() != null
								&& castOther.getContactAddressCountryName() != null
								&& this.getContactAddressCountryName()
										.equals(castOther.getContactAddressCountryName())))
				&& ((this.getContactAddressPhoneNo() == castOther.getContactAddressPhoneNo())
						|| (this.getContactAddressPhoneNo() != null && castOther.getContactAddressPhoneNo() != null
								&& this.getContactAddressPhoneNo().equals(castOther.getContactAddressPhoneNo())))
				&& ((this.getContactAddressMobileNo() == castOther.getContactAddressMobileNo())
						|| (this.getContactAddressMobileNo() != null && castOther.getContactAddressMobileNo() != null
								&& this.getContactAddressMobileNo().equals(castOther.getContactAddressMobileNo())))
				&& ((this.getContactAddressFaxNo() == castOther.getContactAddressFaxNo())
						|| (this.getContactAddressFaxNo() != null && castOther.getContactAddressFaxNo() != null
								&& this.getContactAddressFaxNo().equals(castOther.getContactAddressFaxNo())))
				&& ((this.getContactAddressEmailId() == castOther.getContactAddressEmailId())
						|| (this.getContactAddressEmailId() != null && castOther.getContactAddressEmailId() != null
								&& this.getContactAddressEmailId().equals(castOther.getContactAddressEmailId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getContactAddressTitleName() == null ? 0 : this.getContactAddressTitleName().hashCode());
		result = 37 * result
				+ (getContactAddressStreetName() == null ? 0 : this.getContactAddressStreetName().hashCode());
		result = 37 * result + (getContactAddressAreaName() == null ? 0 : this.getContactAddressAreaName().hashCode());
		result = 37 * result
				+ (getContactAddressLocationName() == null ? 0 : this.getContactAddressLocationName().hashCode());
		result = 37 * result
				+ (getContactAddressStateName() == null ? 0 : this.getContactAddressStateName().hashCode());
		result = 37 * result
				+ (getContactAddressCountryName() == null ? 0 : this.getContactAddressCountryName().hashCode());
		result = 37 * result + (getContactAddressPhoneNo() == null ? 0 : this.getContactAddressPhoneNo().hashCode());
		result = 37 * result + (getContactAddressMobileNo() == null ? 0 : this.getContactAddressMobileNo().hashCode());
		result = 37 * result + (getContactAddressFaxNo() == null ? 0 : this.getContactAddressFaxNo().hashCode());
		result = 37 * result + (getContactAddressEmailId() == null ? 0 : this.getContactAddressEmailId().hashCode());
		return result;
	}

}
