package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CourseQueryId generated by hbm2java
 */
@Embeddable
public class CourseQueryId implements java.io.Serializable {

	private String name;
	private String email;
	private String phone;
	private String queryMessage;
	private String subjectName;

	public CourseQueryId() {
	}

	public CourseQueryId(String name, String email, String phone, String queryMessage, String subjectName) {
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.queryMessage = queryMessage;
		this.subjectName = subjectName;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "query_message", length = 400)
	public String getQueryMessage() {
		return this.queryMessage;
	}

	public void setQueryMessage(String queryMessage) {
		this.queryMessage = queryMessage;
	}

	@Column(name = "subject_name", length = 50)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourseQueryId))
			return false;
		CourseQueryId castOther = (CourseQueryId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getPhone() == castOther.getPhone()) || (this.getPhone() != null
						&& castOther.getPhone() != null && this.getPhone().equals(castOther.getPhone())))
				&& ((this.getQueryMessage() == castOther.getQueryMessage())
						|| (this.getQueryMessage() != null && castOther.getQueryMessage() != null
								&& this.getQueryMessage().equals(castOther.getQueryMessage())))
				&& ((this.getSubjectName() == castOther.getSubjectName())
						|| (this.getSubjectName() != null && castOther.getSubjectName() != null
								&& this.getSubjectName().equals(castOther.getSubjectName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result + (getQueryMessage() == null ? 0 : this.getQueryMessage().hashCode());
		result = 37 * result + (getSubjectName() == null ? 0 : this.getSubjectName().hashCode());
		return result;
	}

}
