package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CourseCandidateDetails generated by hbm2java
 */
@Entity
@Table(name = "course_candidate_details", catalog = "ptutors_db")
public class CourseCandidateDetails implements java.io.Serializable {

	private String applicantEmail;
	private String applicantName;
	private String applicantPassword;
	private String applicantPhone;
	private String applicantAddress;

	public CourseCandidateDetails() {
	}

	public CourseCandidateDetails(String applicantEmail) {
		this.applicantEmail = applicantEmail;
	}

	public CourseCandidateDetails(String applicantEmail, String applicantName, String applicantPassword,
			String applicantPhone, String applicantAddress) {
		this.applicantEmail = applicantEmail;
		this.applicantName = applicantName;
		this.applicantPassword = applicantPassword;
		this.applicantPhone = applicantPhone;
		this.applicantAddress = applicantAddress;
	}

	@Id

	@Column(name = "applicant_email", unique = true, nullable = false, length = 50)
	public String getApplicantEmail() {
		return this.applicantEmail;
	}

	public void setApplicantEmail(String applicantEmail) {
		this.applicantEmail = applicantEmail;
	}

	@Column(name = "applicant_name", length = 50)
	public String getApplicantName() {
		return this.applicantName;
	}

	public void setApplicantName(String applicantName) {
		this.applicantName = applicantName;
	}

	@Column(name = "applicant_password", length = 50)
	public String getApplicantPassword() {
		return this.applicantPassword;
	}

	public void setApplicantPassword(String applicantPassword) {
		this.applicantPassword = applicantPassword;
	}

	@Column(name = "applicant_phone", length = 50)
	public String getApplicantPhone() {
		return this.applicantPhone;
	}

	public void setApplicantPhone(String applicantPhone) {
		this.applicantPhone = applicantPhone;
	}

	@Column(name = "applicantAddress", length = 40)
	public String getApplicantAddress() {
		return this.applicantAddress;
	}

	public void setApplicantAddress(String applicantAddress) {
		this.applicantAddress = applicantAddress;
	}

}
