package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourseName generated by hbm2java
 */
@Entity
@Table(name = "course_name", catalog = "ptutors_db")
public class CourseName implements java.io.Serializable {

	private Integer courseId;
	private String courseType;
	private String courseSubType;
	private String courseShortName;
	private String courseFullName;
	private Set<TutorUgEducation> tutorUgEducations = new HashSet<TutorUgEducation>(0);
	private Set<TutorPgEducation> tutorPgEducations = new HashSet<TutorPgEducation>(0);

	public CourseName() {
	}

	public CourseName(String courseType, String courseShortName) {
		this.courseType = courseType;
		this.courseShortName = courseShortName;
	}

	public CourseName(String courseType, String courseSubType, String courseShortName, String courseFullName,
			Set<TutorUgEducation> tutorUgEducations, Set<TutorPgEducation> tutorPgEducations) {
		this.courseType = courseType;
		this.courseSubType = courseSubType;
		this.courseShortName = courseShortName;
		this.courseFullName = courseFullName;
		this.tutorUgEducations = tutorUgEducations;
		this.tutorPgEducations = tutorPgEducations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "COURSE_ID", unique = true, nullable = false)
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "COURSE_TYPE", nullable = false, length = 5)
	public String getCourseType() {
		return this.courseType;
	}

	public void setCourseType(String courseType) {
		this.courseType = courseType;
	}

	@Column(name = "COURSE_SUB_TYPE", length = 5)
	public String getCourseSubType() {
		return this.courseSubType;
	}

	public void setCourseSubType(String courseSubType) {
		this.courseSubType = courseSubType;
	}

	@Column(name = "COURSE_SHORT_NAME", nullable = false, length = 100)
	public String getCourseShortName() {
		return this.courseShortName;
	}

	public void setCourseShortName(String courseShortName) {
		this.courseShortName = courseShortName;
	}

	@Column(name = "COURSE_FULL_NAME", length = 200)
	public String getCourseFullName() {
		return this.courseFullName;
	}

	public void setCourseFullName(String courseFullName) {
		this.courseFullName = courseFullName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseName")
	public Set<TutorUgEducation> getTutorUgEducations() {
		return this.tutorUgEducations;
	}

	public void setTutorUgEducations(Set<TutorUgEducation> tutorUgEducations) {
		this.tutorUgEducations = tutorUgEducations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courseName")
	public Set<TutorPgEducation> getTutorPgEducations() {
		return this.tutorPgEducations;
	}

	public void setTutorPgEducations(Set<TutorPgEducation> tutorPgEducations) {
		this.tutorPgEducations = tutorPgEducations;
	}

}
