package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CourseQuery generated by hbm2java
 */
@Entity
@Table(name = "course_query", catalog = "ptutors_db")
public class CourseQuery implements java.io.Serializable {

	private CourseQueryId id;

	public CourseQuery() {
	}

	public CourseQuery(CourseQueryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "name", column = @Column(name = "name", length = 50)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 50)),
			@AttributeOverride(name = "phone", column = @Column(name = "phone", length = 20)),
			@AttributeOverride(name = "queryMessage", column = @Column(name = "query_message", length = 400)),
			@AttributeOverride(name = "subjectName", column = @Column(name = "subject_name", length = 50)) })
	public CourseQueryId getId() {
		return this.id;
	}

	public void setId(CourseQueryId id) {
		this.id = id;
	}

}
