package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EducationCategories generated by hbm2java
 */
@Entity
@Table(name = "education_categories", catalog = "ptutors_db")
public class EducationCategories implements java.io.Serializable {

	private Integer educationSegmentId;
	private String educationSegmentName;
	private Set<TutorTeachingSegment> tutorTeachingSegments = new HashSet<TutorTeachingSegment>(0);
	private Set<StudentDetails> studentDetailsesForTutionSegmentId = new HashSet<StudentDetails>(0);
	private Set<StudentDetails> studentDetailsesForEducationSegmentId = new HashSet<StudentDetails>(0);

	public EducationCategories() {
	}

	public EducationCategories(String educationSegmentName) {
		this.educationSegmentName = educationSegmentName;
	}

	public EducationCategories(String educationSegmentName, Set<TutorTeachingSegment> tutorTeachingSegments,
			Set<StudentDetails> studentDetailsesForTutionSegmentId,
			Set<StudentDetails> studentDetailsesForEducationSegmentId) {
		this.educationSegmentName = educationSegmentName;
		this.tutorTeachingSegments = tutorTeachingSegments;
		this.studentDetailsesForTutionSegmentId = studentDetailsesForTutionSegmentId;
		this.studentDetailsesForEducationSegmentId = studentDetailsesForEducationSegmentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EDUCATION_SEGMENT_ID", unique = true, nullable = false)
	public Integer getEducationSegmentId() {
		return this.educationSegmentId;
	}

	public void setEducationSegmentId(Integer educationSegmentId) {
		this.educationSegmentId = educationSegmentId;
	}

	@Column(name = "EDUCATION_SEGMENT_NAME", nullable = false, length = 100)
	public String getEducationSegmentName() {
		return this.educationSegmentName;
	}

	public void setEducationSegmentName(String educationSegmentName) {
		this.educationSegmentName = educationSegmentName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "educationCategories")
	public Set<TutorTeachingSegment> getTutorTeachingSegments() {
		return this.tutorTeachingSegments;
	}

	public void setTutorTeachingSegments(Set<TutorTeachingSegment> tutorTeachingSegments) {
		this.tutorTeachingSegments = tutorTeachingSegments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "educationCategoriesByTutionSegmentId")
	public Set<StudentDetails> getStudentDetailsesForTutionSegmentId() {
		return this.studentDetailsesForTutionSegmentId;
	}

	public void setStudentDetailsesForTutionSegmentId(Set<StudentDetails> studentDetailsesForTutionSegmentId) {
		this.studentDetailsesForTutionSegmentId = studentDetailsesForTutionSegmentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "educationCategoriesByEducationSegmentId")
	public Set<StudentDetails> getStudentDetailsesForEducationSegmentId() {
		return this.studentDetailsesForEducationSegmentId;
	}

	public void setStudentDetailsesForEducationSegmentId(Set<StudentDetails> studentDetailsesForEducationSegmentId) {
		this.studentDetailsesForEducationSegmentId = studentDetailsesForEducationSegmentId;
	}

}
