package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EducationalResources generated by hbm2java
 */
@Entity
@Table(name = "educational_resources", catalog = "ptutors_db")
public class EducationalResources implements java.io.Serializable {

	private int recordId;
	private String title;
	private String description;
	private String websiteUrl;
	private String email;
	private String contactPersonName;
	private String contactNo;
	private Date registrationDate;
	private String organisationName;
	private String menbershipCategory;
	private String duration;
	private String modeOfPayment;
	private BigDecimal paymentAmount;
	private String paymentId;
	private String transactionId;
	private Date paymentDate;
	private Date membershipBeginDate;
	private Date membershipExpireWarningDate;
	private Date membershipExpireDate;

	public EducationalResources() {
	}

	public EducationalResources(int recordId) {
		this.recordId = recordId;
	}

	public EducationalResources(int recordId, String title, String description, String websiteUrl, String email,
			String contactPersonName, String contactNo, Date registrationDate, String organisationName,
			String menbershipCategory, String duration, String modeOfPayment, BigDecimal paymentAmount,
			String paymentId, String transactionId, Date paymentDate, Date membershipBeginDate,
			Date membershipExpireWarningDate, Date membershipExpireDate) {
		this.recordId = recordId;
		this.title = title;
		this.description = description;
		this.websiteUrl = websiteUrl;
		this.email = email;
		this.contactPersonName = contactPersonName;
		this.contactNo = contactNo;
		this.registrationDate = registrationDate;
		this.organisationName = organisationName;
		this.menbershipCategory = menbershipCategory;
		this.duration = duration;
		this.modeOfPayment = modeOfPayment;
		this.paymentAmount = paymentAmount;
		this.paymentId = paymentId;
		this.transactionId = transactionId;
		this.paymentDate = paymentDate;
		this.membershipBeginDate = membershipBeginDate;
		this.membershipExpireWarningDate = membershipExpireWarningDate;
		this.membershipExpireDate = membershipExpireDate;
	}

	@Id

	@Column(name = "record_id", unique = true, nullable = false)
	public int getRecordId() {
		return this.recordId;
	}

	public void setRecordId(int recordId) {
		this.recordId = recordId;
	}

	@Column(name = "title", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "website_url", length = 200)
	public String getWebsiteUrl() {
		return this.websiteUrl;
	}

	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}

	@Column(name = "email", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact_person_name", length = 200)
	public String getContactPersonName() {
		return this.contactPersonName;
	}

	public void setContactPersonName(String contactPersonName) {
		this.contactPersonName = contactPersonName;
	}

	@Column(name = "contact_no", length = 11)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "registration_date", length = 10)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "organisation_name", length = 100)
	public String getOrganisationName() {
		return this.organisationName;
	}

	public void setOrganisationName(String organisationName) {
		this.organisationName = organisationName;
	}

	@Column(name = "menbership_category", length = 100)
	public String getMenbershipCategory() {
		return this.menbershipCategory;
	}

	public void setMenbershipCategory(String menbershipCategory) {
		this.menbershipCategory = menbershipCategory;
	}

	@Column(name = "duration", length = 100)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "mode_of_payment", length = 100)
	public String getModeOfPayment() {
		return this.modeOfPayment;
	}

	public void setModeOfPayment(String modeOfPayment) {
		this.modeOfPayment = modeOfPayment;
	}

	@Column(name = "payment_amount", precision = 10)
	public BigDecimal getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(BigDecimal paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Column(name = "payment_id", length = 20)
	public String getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "transaction_id", length = 20)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payment_date", length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "membership_begin_date", length = 10)
	public Date getMembershipBeginDate() {
		return this.membershipBeginDate;
	}

	public void setMembershipBeginDate(Date membershipBeginDate) {
		this.membershipBeginDate = membershipBeginDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "membership_expire_warning_date", length = 10)
	public Date getMembershipExpireWarningDate() {
		return this.membershipExpireWarningDate;
	}

	public void setMembershipExpireWarningDate(Date membershipExpireWarningDate) {
		this.membershipExpireWarningDate = membershipExpireWarningDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "membership_expire_date", length = 10)
	public Date getMembershipExpireDate() {
		return this.membershipExpireDate;
	}

	public void setMembershipExpireDate(Date membershipExpireDate) {
		this.membershipExpireDate = membershipExpireDate;
	}

}
