package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployersDetails generated by hbm2java
 */
@Entity
@Table(name = "employers_details", catalog = "ptutors_db")
public class EmployersDetails implements java.io.Serializable {

	private String employeeId;
	private String name;
	private String userLoginName;
	private String password;
	private String secretQuestion;
	private String secretQuestionAnswer;
	private Character gender;
	private Integer age;
	private String countryCode;
	private String locationId;
	private String postalCode;
	private String stateProvince;
	private String address;
	private String companyName;
	private int companyNameId;
	private int industryId;
	private String contactPersonName;
	private String contactNumber;
	private String emailAddress;
	private String membershipCategory;
	private Integer duration;
	private String modeOfPayment;
	private BigDecimal paymentAmount;
	private String paymentId;
	private String transactionId;
	private Date paymentDate;
	private Date membershipBeginDate;
	private Date membershipExpireWarningDate;
	private Date membershipExpireDate;

	public EmployersDetails() {
	}

	public EmployersDetails(String employeeId, int companyNameId, int industryId) {
		this.employeeId = employeeId;
		this.companyNameId = companyNameId;
		this.industryId = industryId;
	}

	public EmployersDetails(String employeeId, String name, String userLoginName, String password,
			String secretQuestion, String secretQuestionAnswer, Character gender, Integer age, String countryCode,
			String locationId, String postalCode, String stateProvince, String address, String companyName,
			int companyNameId, int industryId, String contactPersonName, String contactNumber, String emailAddress,
			String membershipCategory, Integer duration, String modeOfPayment, BigDecimal paymentAmount,
			String paymentId, String transactionId, Date paymentDate, Date membershipBeginDate,
			Date membershipExpireWarningDate, Date membershipExpireDate) {
		this.employeeId = employeeId;
		this.name = name;
		this.userLoginName = userLoginName;
		this.password = password;
		this.secretQuestion = secretQuestion;
		this.secretQuestionAnswer = secretQuestionAnswer;
		this.gender = gender;
		this.age = age;
		this.countryCode = countryCode;
		this.locationId = locationId;
		this.postalCode = postalCode;
		this.stateProvince = stateProvince;
		this.address = address;
		this.companyName = companyName;
		this.companyNameId = companyNameId;
		this.industryId = industryId;
		this.contactPersonName = contactPersonName;
		this.contactNumber = contactNumber;
		this.emailAddress = emailAddress;
		this.membershipCategory = membershipCategory;
		this.duration = duration;
		this.modeOfPayment = modeOfPayment;
		this.paymentAmount = paymentAmount;
		this.paymentId = paymentId;
		this.transactionId = transactionId;
		this.paymentDate = paymentDate;
		this.membershipBeginDate = membershipBeginDate;
		this.membershipExpireWarningDate = membershipExpireWarningDate;
		this.membershipExpireDate = membershipExpireDate;
	}

	@Id

	@Column(name = "employee_Id", unique = true, nullable = false, length = 10)
	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "user_login_name", length = 20)
	public String getUserLoginName() {
		return this.userLoginName;
	}

	public void setUserLoginName(String userLoginName) {
		this.userLoginName = userLoginName;
	}

	@Column(name = "password", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "secret_question", length = 200)
	public String getSecretQuestion() {
		return this.secretQuestion;
	}

	public void setSecretQuestion(String secretQuestion) {
		this.secretQuestion = secretQuestion;
	}

	@Column(name = "secret_question_answer", length = 200)
	public String getSecretQuestionAnswer() {
		return this.secretQuestionAnswer;
	}

	public void setSecretQuestionAnswer(String secretQuestionAnswer) {
		this.secretQuestionAnswer = secretQuestionAnswer;
	}

	@Column(name = "gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "country_code", length = 4)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "location_id", length = 10)
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	@Column(name = "postal_code", length = 50)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "state_province", length = 200)
	public String getStateProvince() {
		return this.stateProvince;
	}

	public void setStateProvince(String stateProvince) {
		this.stateProvince = stateProvince;
	}

	@Column(name = "address", length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "company_name", length = 100)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "company_name_id", nullable = false)
	public int getCompanyNameId() {
		return this.companyNameId;
	}

	public void setCompanyNameId(int companyNameId) {
		this.companyNameId = companyNameId;
	}

	@Column(name = "industry_id", nullable = false)
	public int getIndustryId() {
		return this.industryId;
	}

	public void setIndustryId(int industryId) {
		this.industryId = industryId;
	}

	@Column(name = "contact_person_name", length = 50)
	public String getContactPersonName() {
		return this.contactPersonName;
	}

	public void setContactPersonName(String contactPersonName) {
		this.contactPersonName = contactPersonName;
	}

	@Column(name = "contact_number", length = 11)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "email_address", length = 200)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "MEMBERSHIP_CATEGORY", length = 100)
	public String getMembershipCategory() {
		return this.membershipCategory;
	}

	public void setMembershipCategory(String membershipCategory) {
		this.membershipCategory = membershipCategory;
	}

	@Column(name = "DURATION")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "MODE_OF_PAYMENT", length = 200)
	public String getModeOfPayment() {
		return this.modeOfPayment;
	}

	public void setModeOfPayment(String modeOfPayment) {
		this.modeOfPayment = modeOfPayment;
	}

	@Column(name = "PAYMENT_AMOUNT", precision = 10)
	public BigDecimal getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(BigDecimal paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Column(name = "PAYMENT_ID", length = 10)
	public String getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "TRANSACTION_ID", length = 20)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAYMENT_DATE", length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_BEGIN_DATE", length = 10)
	public Date getMembershipBeginDate() {
		return this.membershipBeginDate;
	}

	public void setMembershipBeginDate(Date membershipBeginDate) {
		this.membershipBeginDate = membershipBeginDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_EXPIRE_WARNING_DATE", length = 10)
	public Date getMembershipExpireWarningDate() {
		return this.membershipExpireWarningDate;
	}

	public void setMembershipExpireWarningDate(Date membershipExpireWarningDate) {
		this.membershipExpireWarningDate = membershipExpireWarningDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_EXPIRE_DATE", length = 10)
	public Date getMembershipExpireDate() {
		return this.membershipExpireDate;
	}

	public void setMembershipExpireDate(Date membershipExpireDate) {
		this.membershipExpireDate = membershipExpireDate;
	}

}
