package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InstituteSubCategory generated by hbm2java
 */
@Entity
@Table(name = "institute_sub_category", catalog = "ptutors_db")
public class InstituteSubCategory implements java.io.Serializable {

	private int instituteSubCategoryId;
	private Integer instituteCategoryId;
	private String instituteSubCategoryName;

	public InstituteSubCategory() {
	}

	public InstituteSubCategory(int instituteSubCategoryId) {
		this.instituteSubCategoryId = instituteSubCategoryId;
	}

	public InstituteSubCategory(int instituteSubCategoryId, Integer instituteCategoryId,
			String instituteSubCategoryName) {
		this.instituteSubCategoryId = instituteSubCategoryId;
		this.instituteCategoryId = instituteCategoryId;
		this.instituteSubCategoryName = instituteSubCategoryName;
	}

	@Id

	@Column(name = "INSTITUTE_SUB_CATEGORY_ID", unique = true, nullable = false)
	public int getInstituteSubCategoryId() {
		return this.instituteSubCategoryId;
	}

	public void setInstituteSubCategoryId(int instituteSubCategoryId) {
		this.instituteSubCategoryId = instituteSubCategoryId;
	}

	@Column(name = "INSTITUTE_CATEGORY_ID")
	public Integer getInstituteCategoryId() {
		return this.instituteCategoryId;
	}

	public void setInstituteCategoryId(Integer instituteCategoryId) {
		this.instituteCategoryId = instituteCategoryId;
	}

	@Column(name = "INSTITUTE_SUB_CATEGORY_NAME", length = 200)
	public String getInstituteSubCategoryName() {
		return this.instituteSubCategoryName;
	}

	public void setInstituteSubCategoryName(String instituteSubCategoryName) {
		this.instituteSubCategoryName = instituteSubCategoryName;
	}

}
