package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobseekersDetails generated by hbm2java
 */
@Entity
@Table(name = "jobseekers_details", catalog = "ptutors_db")
public class JobseekersDetails implements java.io.Serializable {

	private String jobseekerId;
	private String name;
	private String userLoginName;
	private String password;
	private Integer secretQuestionId;
	private String secretQuestionAnswer;
	private Character gender;
	private Integer age;
	private String countryCode;
	private Integer locationId;
	private String areaName;
	private String postalCode;
	private String stateProvince;
	private String address;
	private String contactNumber;
	private String emailAddress;
	private Integer yearsOfTutoringExperience;
	private String preferredTutoringArea;
	private String expectedFees;
	private String tutoringExperience;
	private Integer industryType;
	private Integer salaryInThousand;
	private String keySkills;
	private Date registrationDate;
	private Byte imageFlag;
	private Boolean profileVerificationStatus;
	private Boolean profileActiveDeactiveStatus;
	private String membershipCategory;
	private Integer duration;
	private String modeOfPayment;
	private BigDecimal paymentAmount;
	private String paymentId;
	private String transactionId;
	private Date paymentDate;
	private Date membershipBeginDate;
	private Date membershipExpireWarningDate;
	private Date membershipExpireDate;
	private Integer ugDegree;
	private Integer ugSpecialization;
	private Integer ugUniversity;
	private String ugPassoutYear;
	private Integer pgDegree;
	private Integer pgSpecialization;
	private Integer pgUniversity;
	private String pgPassoutYear;
	private String currentEmployer;
	private String preferredRole;
	private String perviousEmployer;
	private String resumeHeadline;
	private String resumePath;

	public JobseekersDetails() {
	}

	public JobseekersDetails(String jobseekerId) {
		this.jobseekerId = jobseekerId;
	}

	public JobseekersDetails(String jobseekerId, String name, String userLoginName, String password,
			Integer secretQuestionId, String secretQuestionAnswer, Character gender, Integer age, String countryCode,
			Integer locationId, String areaName, String postalCode, String stateProvince, String address,
			String contactNumber, String emailAddress, Integer yearsOfTutoringExperience, String preferredTutoringArea,
			String expectedFees, String tutoringExperience, Integer industryType, Integer salaryInThousand,
			String keySkills, Date registrationDate, Byte imageFlag, Boolean profileVerificationStatus,
			Boolean profileActiveDeactiveStatus, String membershipCategory, Integer duration, String modeOfPayment,
			BigDecimal paymentAmount, String paymentId, String transactionId, Date paymentDate,
			Date membershipBeginDate, Date membershipExpireWarningDate, Date membershipExpireDate, Integer ugDegree,
			Integer ugSpecialization, Integer ugUniversity, String ugPassoutYear, Integer pgDegree,
			Integer pgSpecialization, Integer pgUniversity, String pgPassoutYear, String currentEmployer,
			String preferredRole, String perviousEmployer, String resumeHeadline, String resumePath) {
		this.jobseekerId = jobseekerId;
		this.name = name;
		this.userLoginName = userLoginName;
		this.password = password;
		this.secretQuestionId = secretQuestionId;
		this.secretQuestionAnswer = secretQuestionAnswer;
		this.gender = gender;
		this.age = age;
		this.countryCode = countryCode;
		this.locationId = locationId;
		this.areaName = areaName;
		this.postalCode = postalCode;
		this.stateProvince = stateProvince;
		this.address = address;
		this.contactNumber = contactNumber;
		this.emailAddress = emailAddress;
		this.yearsOfTutoringExperience = yearsOfTutoringExperience;
		this.preferredTutoringArea = preferredTutoringArea;
		this.expectedFees = expectedFees;
		this.tutoringExperience = tutoringExperience;
		this.industryType = industryType;
		this.salaryInThousand = salaryInThousand;
		this.keySkills = keySkills;
		this.registrationDate = registrationDate;
		this.imageFlag = imageFlag;
		this.profileVerificationStatus = profileVerificationStatus;
		this.profileActiveDeactiveStatus = profileActiveDeactiveStatus;
		this.membershipCategory = membershipCategory;
		this.duration = duration;
		this.modeOfPayment = modeOfPayment;
		this.paymentAmount = paymentAmount;
		this.paymentId = paymentId;
		this.transactionId = transactionId;
		this.paymentDate = paymentDate;
		this.membershipBeginDate = membershipBeginDate;
		this.membershipExpireWarningDate = membershipExpireWarningDate;
		this.membershipExpireDate = membershipExpireDate;
		this.ugDegree = ugDegree;
		this.ugSpecialization = ugSpecialization;
		this.ugUniversity = ugUniversity;
		this.ugPassoutYear = ugPassoutYear;
		this.pgDegree = pgDegree;
		this.pgSpecialization = pgSpecialization;
		this.pgUniversity = pgUniversity;
		this.pgPassoutYear = pgPassoutYear;
		this.currentEmployer = currentEmployer;
		this.preferredRole = preferredRole;
		this.perviousEmployer = perviousEmployer;
		this.resumeHeadline = resumeHeadline;
		this.resumePath = resumePath;
	}

	@Id

	@Column(name = "JOBSEEKER_ID", unique = true, nullable = false, length = 10)
	public String getJobseekerId() {
		return this.jobseekerId;
	}

	public void setJobseekerId(String jobseekerId) {
		this.jobseekerId = jobseekerId;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "USER_LOGIN_NAME", length = 20)
	public String getUserLoginName() {
		return this.userLoginName;
	}

	public void setUserLoginName(String userLoginName) {
		this.userLoginName = userLoginName;
	}

	@Column(name = "PASSWORD", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "SECRET_QUESTION_ID")
	public Integer getSecretQuestionId() {
		return this.secretQuestionId;
	}

	public void setSecretQuestionId(Integer secretQuestionId) {
		this.secretQuestionId = secretQuestionId;
	}

	@Column(name = "SECRET_QUESTION_ANSWER", length = 200)
	public String getSecretQuestionAnswer() {
		return this.secretQuestionAnswer;
	}

	public void setSecretQuestionAnswer(String secretQuestionAnswer) {
		this.secretQuestionAnswer = secretQuestionAnswer;
	}

	@Column(name = "GENDER", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "AGE")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "COUNTRY_CODE", length = 4)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "LOCATION_ID")
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	@Column(name = "AREA_NAME", length = 200)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "POSTAL_CODE", length = 50)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "STATE_PROVINCE", length = 200)
	public String getStateProvince() {
		return this.stateProvince;
	}

	public void setStateProvince(String stateProvince) {
		this.stateProvince = stateProvince;
	}

	@Column(name = "ADDRESS", length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CONTACT_NUMBER", length = 100)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "EMAIL_ADDRESS", length = 200)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "YEARS_OF_TUTORING_EXPERIENCE")
	public Integer getYearsOfTutoringExperience() {
		return this.yearsOfTutoringExperience;
	}

	public void setYearsOfTutoringExperience(Integer yearsOfTutoringExperience) {
		this.yearsOfTutoringExperience = yearsOfTutoringExperience;
	}

	@Column(name = "PREFERRED_TUTORING_AREA", length = 200)
	public String getPreferredTutoringArea() {
		return this.preferredTutoringArea;
	}

	public void setPreferredTutoringArea(String preferredTutoringArea) {
		this.preferredTutoringArea = preferredTutoringArea;
	}

	@Column(name = "EXPECTED_FEES", length = 100)
	public String getExpectedFees() {
		return this.expectedFees;
	}

	public void setExpectedFees(String expectedFees) {
		this.expectedFees = expectedFees;
	}

	@Column(name = "TUTORING_EXPERIENCE", length = 500)
	public String getTutoringExperience() {
		return this.tutoringExperience;
	}

	public void setTutoringExperience(String tutoringExperience) {
		this.tutoringExperience = tutoringExperience;
	}

	@Column(name = "INDUSTRY_TYPE")
	public Integer getIndustryType() {
		return this.industryType;
	}

	public void setIndustryType(Integer industryType) {
		this.industryType = industryType;
	}

	@Column(name = "SALARY_IN_THOUSAND")
	public Integer getSalaryInThousand() {
		return this.salaryInThousand;
	}

	public void setSalaryInThousand(Integer salaryInThousand) {
		this.salaryInThousand = salaryInThousand;
	}

	@Column(name = "KEY_SKILLS", length = 100)
	public String getKeySkills() {
		return this.keySkills;
	}

	public void setKeySkills(String keySkills) {
		this.keySkills = keySkills;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REGISTRATION_DATE", length = 10)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "IMAGE_FLAG")
	public Byte getImageFlag() {
		return this.imageFlag;
	}

	public void setImageFlag(Byte imageFlag) {
		this.imageFlag = imageFlag;
	}

	@Column(name = "PROFILE_VERIFICATION_STATUS")
	public Boolean getProfileVerificationStatus() {
		return this.profileVerificationStatus;
	}

	public void setProfileVerificationStatus(Boolean profileVerificationStatus) {
		this.profileVerificationStatus = profileVerificationStatus;
	}

	@Column(name = "PROFILE_ACTIVE_DEACTIVE_STATUS")
	public Boolean getProfileActiveDeactiveStatus() {
		return this.profileActiveDeactiveStatus;
	}

	public void setProfileActiveDeactiveStatus(Boolean profileActiveDeactiveStatus) {
		this.profileActiveDeactiveStatus = profileActiveDeactiveStatus;
	}

	@Column(name = "MEMBERSHIP_CATEGORY", length = 100)
	public String getMembershipCategory() {
		return this.membershipCategory;
	}

	public void setMembershipCategory(String membershipCategory) {
		this.membershipCategory = membershipCategory;
	}

	@Column(name = "DURATION")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "MODE_OF_PAYMENT", length = 200)
	public String getModeOfPayment() {
		return this.modeOfPayment;
	}

	public void setModeOfPayment(String modeOfPayment) {
		this.modeOfPayment = modeOfPayment;
	}

	@Column(name = "PAYMENT_AMOUNT", precision = 10)
	public BigDecimal getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(BigDecimal paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Column(name = "PAYMENT_ID", length = 20)
	public String getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "TRANSACTION_ID", length = 20)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAYMENT_DATE", length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_BEGIN_DATE", length = 10)
	public Date getMembershipBeginDate() {
		return this.membershipBeginDate;
	}

	public void setMembershipBeginDate(Date membershipBeginDate) {
		this.membershipBeginDate = membershipBeginDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_EXPIRE_WARNING_DATE", length = 10)
	public Date getMembershipExpireWarningDate() {
		return this.membershipExpireWarningDate;
	}

	public void setMembershipExpireWarningDate(Date membershipExpireWarningDate) {
		this.membershipExpireWarningDate = membershipExpireWarningDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_EXPIRE_DATE", length = 10)
	public Date getMembershipExpireDate() {
		return this.membershipExpireDate;
	}

	public void setMembershipExpireDate(Date membershipExpireDate) {
		this.membershipExpireDate = membershipExpireDate;
	}

	@Column(name = "UG_DEGREE")
	public Integer getUgDegree() {
		return this.ugDegree;
	}

	public void setUgDegree(Integer ugDegree) {
		this.ugDegree = ugDegree;
	}

	@Column(name = "UG_SPECIALIZATION")
	public Integer getUgSpecialization() {
		return this.ugSpecialization;
	}

	public void setUgSpecialization(Integer ugSpecialization) {
		this.ugSpecialization = ugSpecialization;
	}

	@Column(name = "UG_UNIVERSITY")
	public Integer getUgUniversity() {
		return this.ugUniversity;
	}

	public void setUgUniversity(Integer ugUniversity) {
		this.ugUniversity = ugUniversity;
	}

	@Column(name = "UG_PASSOUT_YEAR", length = 4)
	public String getUgPassoutYear() {
		return this.ugPassoutYear;
	}

	public void setUgPassoutYear(String ugPassoutYear) {
		this.ugPassoutYear = ugPassoutYear;
	}

	@Column(name = "PG_DEGREE")
	public Integer getPgDegree() {
		return this.pgDegree;
	}

	public void setPgDegree(Integer pgDegree) {
		this.pgDegree = pgDegree;
	}

	@Column(name = "PG_SPECIALIZATION")
	public Integer getPgSpecialization() {
		return this.pgSpecialization;
	}

	public void setPgSpecialization(Integer pgSpecialization) {
		this.pgSpecialization = pgSpecialization;
	}

	@Column(name = "PG_UNIVERSITY")
	public Integer getPgUniversity() {
		return this.pgUniversity;
	}

	public void setPgUniversity(Integer pgUniversity) {
		this.pgUniversity = pgUniversity;
	}

	@Column(name = "PG_PASSOUT_YEAR", length = 4)
	public String getPgPassoutYear() {
		return this.pgPassoutYear;
	}

	public void setPgPassoutYear(String pgPassoutYear) {
		this.pgPassoutYear = pgPassoutYear;
	}

	@Column(name = "CURRENT_EMPLOYER", length = 100)
	public String getCurrentEmployer() {
		return this.currentEmployer;
	}

	public void setCurrentEmployer(String currentEmployer) {
		this.currentEmployer = currentEmployer;
	}

	@Column(name = "PREFERRED_ROLE", length = 100)
	public String getPreferredRole() {
		return this.preferredRole;
	}

	public void setPreferredRole(String preferredRole) {
		this.preferredRole = preferredRole;
	}

	@Column(name = "PERVIOUS_EMPLOYER", length = 100)
	public String getPerviousEmployer() {
		return this.perviousEmployer;
	}

	public void setPerviousEmployer(String perviousEmployer) {
		this.perviousEmployer = perviousEmployer;
	}

	@Column(name = "RESUME_HEADLINE", length = 100)
	public String getResumeHeadline() {
		return this.resumeHeadline;
	}

	public void setResumeHeadline(String resumeHeadline) {
		this.resumeHeadline = resumeHeadline;
	}

	@Column(name = "RESUME_PATH", length = 500)
	public String getResumePath() {
		return this.resumePath;
	}

	public void setResumePath(String resumePath) {
		this.resumePath = resumePath;
	}

}
