package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JobseekerFunctionalArea generated by hbm2java
 */
@Entity
@Table(name = "jobseeker_functional_area", catalog = "ptutors_db")
public class JobseekerFunctionalArea implements java.io.Serializable {

	private Integer functionalAreaId;
	private String jobseekerId;
	private int functionalArea;

	public JobseekerFunctionalArea() {
	}

	public JobseekerFunctionalArea(String jobseekerId, int functionalArea) {
		this.jobseekerId = jobseekerId;
		this.functionalArea = functionalArea;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FUNCTIONAL_AREA_ID", unique = true, nullable = false)
	public Integer getFunctionalAreaId() {
		return this.functionalAreaId;
	}

	public void setFunctionalAreaId(Integer functionalAreaId) {
		this.functionalAreaId = functionalAreaId;
	}

	@Column(name = "JOBSEEKER_ID", nullable = false, length = 10)
	public String getJobseekerId() {
		return this.jobseekerId;
	}

	public void setJobseekerId(String jobseekerId) {
		this.jobseekerId = jobseekerId;
	}

	@Column(name = "FUNCTIONAL_AREA", nullable = false)
	public int getFunctionalArea() {
		return this.functionalArea;
	}

	public void setFunctionalArea(int functionalArea) {
		this.functionalArea = functionalArea;
	}

}
