package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PostAdvertisement generated by hbm2java
 */
@Entity
@Table(name = "post_advertisement", catalog = "ptutors_db")
public class PostAdvertisement implements java.io.Serializable {

	private String adverId;
	private String adverName;
	private String adverContactNumber;
	private String adverEmailAddress;
	private String adverLocationName;
	private String adverCountryName;
	private String adverPostalCode;
	private String adverAddress;
	private String adverType;
	private byte[] adverImage;
	private Boolean adverVerificationStatus;
	private Boolean adverActiveStatus;
	private String adverMembershipCategory;
	private String adverDuration;
	private String adverModeOfPayment;
	private String adverOrderBillNo;
	private String adverPaymentAmount;
	private Date adverPostingDate;
	private Date advrExpireWarningDate;
	private Date advrExpireDate;
	private String adverCategory;
	private String adverTitle;
	private String adverCityId;
	private String adverDescription;
	private Date adverTime;
	private Byte imageFlag;

	public PostAdvertisement() {
	}

	public PostAdvertisement(String adverId) {
		this.adverId = adverId;
	}

	public PostAdvertisement(String adverId, String adverName, String adverContactNumber, String adverEmailAddress,
			String adverLocationName, String adverCountryName, String adverPostalCode, String adverAddress,
			String adverType, byte[] adverImage, Boolean adverVerificationStatus, Boolean adverActiveStatus,
			String adverMembershipCategory, String adverDuration, String adverModeOfPayment, String adverOrderBillNo,
			String adverPaymentAmount, Date adverPostingDate, Date advrExpireWarningDate, Date advrExpireDate,
			String adverCategory, String adverTitle, String adverCityId, String adverDescription, Date adverTime,
			Byte imageFlag) {
		this.adverId = adverId;
		this.adverName = adverName;
		this.adverContactNumber = adverContactNumber;
		this.adverEmailAddress = adverEmailAddress;
		this.adverLocationName = adverLocationName;
		this.adverCountryName = adverCountryName;
		this.adverPostalCode = adverPostalCode;
		this.adverAddress = adverAddress;
		this.adverType = adverType;
		this.adverImage = adverImage;
		this.adverVerificationStatus = adverVerificationStatus;
		this.adverActiveStatus = adverActiveStatus;
		this.adverMembershipCategory = adverMembershipCategory;
		this.adverDuration = adverDuration;
		this.adverModeOfPayment = adverModeOfPayment;
		this.adverOrderBillNo = adverOrderBillNo;
		this.adverPaymentAmount = adverPaymentAmount;
		this.adverPostingDate = adverPostingDate;
		this.advrExpireWarningDate = advrExpireWarningDate;
		this.advrExpireDate = advrExpireDate;
		this.adverCategory = adverCategory;
		this.adverTitle = adverTitle;
		this.adverCityId = adverCityId;
		this.adverDescription = adverDescription;
		this.adverTime = adverTime;
		this.imageFlag = imageFlag;
	}

	@Id

	@Column(name = "adver_id", unique = true, nullable = false, length = 20)
	public String getAdverId() {
		return this.adverId;
	}

	public void setAdverId(String adverId) {
		this.adverId = adverId;
	}

	@Column(name = "adver_name", length = 200)
	public String getAdverName() {
		return this.adverName;
	}

	public void setAdverName(String adverName) {
		this.adverName = adverName;
	}

	@Column(name = "adver_contact_number", length = 50)
	public String getAdverContactNumber() {
		return this.adverContactNumber;
	}

	public void setAdverContactNumber(String adverContactNumber) {
		this.adverContactNumber = adverContactNumber;
	}

	@Column(name = "adver_email_address", length = 50)
	public String getAdverEmailAddress() {
		return this.adverEmailAddress;
	}

	public void setAdverEmailAddress(String adverEmailAddress) {
		this.adverEmailAddress = adverEmailAddress;
	}

	@Column(name = "adver_location_name", length = 200)
	public String getAdverLocationName() {
		return this.adverLocationName;
	}

	public void setAdverLocationName(String adverLocationName) {
		this.adverLocationName = adverLocationName;
	}

	@Column(name = "adver_country_name", length = 100)
	public String getAdverCountryName() {
		return this.adverCountryName;
	}

	public void setAdverCountryName(String adverCountryName) {
		this.adverCountryName = adverCountryName;
	}

	@Column(name = "adver_postal_code", length = 50)
	public String getAdverPostalCode() {
		return this.adverPostalCode;
	}

	public void setAdverPostalCode(String adverPostalCode) {
		this.adverPostalCode = adverPostalCode;
	}

	@Column(name = "adver_address", length = 300)
	public String getAdverAddress() {
		return this.adverAddress;
	}

	public void setAdverAddress(String adverAddress) {
		this.adverAddress = adverAddress;
	}

	@Column(name = "adver_type", length = 300)
	public String getAdverType() {
		return this.adverType;
	}

	public void setAdverType(String adverType) {
		this.adverType = adverType;
	}

	@Column(name = "adver_image")
	public byte[] getAdverImage() {
		return this.adverImage;
	}

	public void setAdverImage(byte[] adverImage) {
		this.adverImage = adverImage;
	}

	@Column(name = "adver_verification_status")
	public Boolean getAdverVerificationStatus() {
		return this.adverVerificationStatus;
	}

	public void setAdverVerificationStatus(Boolean adverVerificationStatus) {
		this.adverVerificationStatus = adverVerificationStatus;
	}

	@Column(name = "adver_active_status")
	public Boolean getAdverActiveStatus() {
		return this.adverActiveStatus;
	}

	public void setAdverActiveStatus(Boolean adverActiveStatus) {
		this.adverActiveStatus = adverActiveStatus;
	}

	@Column(name = "adver_membership_category", length = 300)
	public String getAdverMembershipCategory() {
		return this.adverMembershipCategory;
	}

	public void setAdverMembershipCategory(String adverMembershipCategory) {
		this.adverMembershipCategory = adverMembershipCategory;
	}

	@Column(name = "adver_duration", length = 20)
	public String getAdverDuration() {
		return this.adverDuration;
	}

	public void setAdverDuration(String adverDuration) {
		this.adverDuration = adverDuration;
	}

	@Column(name = "adver_mode_of_payment", length = 200)
	public String getAdverModeOfPayment() {
		return this.adverModeOfPayment;
	}

	public void setAdverModeOfPayment(String adverModeOfPayment) {
		this.adverModeOfPayment = adverModeOfPayment;
	}

	@Column(name = "adver_order_bill_no", length = 300)
	public String getAdverOrderBillNo() {
		return this.adverOrderBillNo;
	}

	public void setAdverOrderBillNo(String adverOrderBillNo) {
		this.adverOrderBillNo = adverOrderBillNo;
	}

	@Column(name = "adver_payment_amount", length = 100)
	public String getAdverPaymentAmount() {
		return this.adverPaymentAmount;
	}

	public void setAdverPaymentAmount(String adverPaymentAmount) {
		this.adverPaymentAmount = adverPaymentAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adver_posting_date", length = 10)
	public Date getAdverPostingDate() {
		return this.adverPostingDate;
	}

	public void setAdverPostingDate(Date adverPostingDate) {
		this.adverPostingDate = adverPostingDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "advr_expire_warning_date", length = 10)
	public Date getAdvrExpireWarningDate() {
		return this.advrExpireWarningDate;
	}

	public void setAdvrExpireWarningDate(Date advrExpireWarningDate) {
		this.advrExpireWarningDate = advrExpireWarningDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "advr_expire_date", length = 10)
	public Date getAdvrExpireDate() {
		return this.advrExpireDate;
	}

	public void setAdvrExpireDate(Date advrExpireDate) {
		this.advrExpireDate = advrExpireDate;
	}

	@Column(name = "adver_category", length = 100)
	public String getAdverCategory() {
		return this.adverCategory;
	}

	public void setAdverCategory(String adverCategory) {
		this.adverCategory = adverCategory;
	}

	@Column(name = "adver_title", length = 100)
	public String getAdverTitle() {
		return this.adverTitle;
	}

	public void setAdverTitle(String adverTitle) {
		this.adverTitle = adverTitle;
	}

	@Column(name = "adver_city_id", length = 100)
	public String getAdverCityId() {
		return this.adverCityId;
	}

	public void setAdverCityId(String adverCityId) {
		this.adverCityId = adverCityId;
	}

	@Column(name = "adver_description", length = 50000)
	public String getAdverDescription() {
		return this.adverDescription;
	}

	public void setAdverDescription(String adverDescription) {
		this.adverDescription = adverDescription;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "adver_time", length = 8)
	public Date getAdverTime() {
		return this.adverTime;
	}

	public void setAdverTime(Date adverTime) {
		this.adverTime = adverTime;
	}

	@Column(name = "image_flag")
	public Byte getImageFlag() {
		return this.imageFlag;
	}

	public void setImageFlag(Byte imageFlag) {
		this.imageFlag = imageFlag;
	}

}
