package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SchoolBoard generated by hbm2java
 */
@Entity
@Table(name = "school_board", catalog = "ptutors_db")
public class SchoolBoard implements java.io.Serializable {

	private int schoolBoardId;
	private CountryName countryName;
	private LocationName locationName;
	private String schoolBoardName;
	private Set<StudentDetails> studentDetailses = new HashSet<StudentDetails>(0);

	public SchoolBoard() {
	}

	public SchoolBoard(int schoolBoardId) {
		this.schoolBoardId = schoolBoardId;
	}

	public SchoolBoard(int schoolBoardId, CountryName countryName, LocationName locationName, String schoolBoardName,
			Set<StudentDetails> studentDetailses) {
		this.schoolBoardId = schoolBoardId;
		this.countryName = countryName;
		this.locationName = locationName;
		this.schoolBoardName = schoolBoardName;
		this.studentDetailses = studentDetailses;
	}

	@Id

	@Column(name = "school_board_id", unique = true, nullable = false)
	public int getSchoolBoardId() {
		return this.schoolBoardId;
	}

	public void setSchoolBoardId(int schoolBoardId) {
		this.schoolBoardId = schoolBoardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_code")
	public CountryName getCountryName() {
		return this.countryName;
	}

	public void setCountryName(CountryName countryName) {
		this.countryName = countryName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id")
	public LocationName getLocationName() {
		return this.locationName;
	}

	public void setLocationName(LocationName locationName) {
		this.locationName = locationName;
	}

	@Column(name = "school_board_name", length = 200)
	public String getSchoolBoardName() {
		return this.schoolBoardName;
	}

	public void setSchoolBoardName(String schoolBoardName) {
		this.schoolBoardName = schoolBoardName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schoolBoard")
	public Set<StudentDetails> getStudentDetailses() {
		return this.studentDetailses;
	}

	public void setStudentDetailses(Set<StudentDetails> studentDetailses) {
		this.studentDetailses = studentDetailses;
	}

}
