package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SecretQuestion generated by hbm2java
 */
@Entity
@Table(name = "secret_question", catalog = "ptutors_db")
public class SecretQuestion implements java.io.Serializable {

	private int secretQuestionId;
	private String secretQuestionValue;
	private Set<StudentDetails> studentDetailses = new HashSet<StudentDetails>(0);
	private Set<TutorialCenter> tutorialCenters = new HashSet<TutorialCenter>(0);

	public SecretQuestion() {
	}

	public SecretQuestion(int secretQuestionId, String secretQuestionValue) {
		this.secretQuestionId = secretQuestionId;
		this.secretQuestionValue = secretQuestionValue;
	}

	public SecretQuestion(int secretQuestionId, String secretQuestionValue, Set<StudentDetails> studentDetailses,
			Set<TutorialCenter> tutorialCenters) {
		this.secretQuestionId = secretQuestionId;
		this.secretQuestionValue = secretQuestionValue;
		this.studentDetailses = studentDetailses;
		this.tutorialCenters = tutorialCenters;
	}

	@Id

	@Column(name = "SECRET_QUESTION_ID", unique = true, nullable = false)
	public int getSecretQuestionId() {
		return this.secretQuestionId;
	}

	public void setSecretQuestionId(int secretQuestionId) {
		this.secretQuestionId = secretQuestionId;
	}

	@Column(name = "SECRET_QUESTION_VALUE", nullable = false, length = 200)
	public String getSecretQuestionValue() {
		return this.secretQuestionValue;
	}

	public void setSecretQuestionValue(String secretQuestionValue) {
		this.secretQuestionValue = secretQuestionValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secretQuestion")
	public Set<StudentDetails> getStudentDetailses() {
		return this.studentDetailses;
	}

	public void setStudentDetailses(Set<StudentDetails> studentDetailses) {
		this.studentDetailses = studentDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secretQuestion")
	public Set<TutorialCenter> getTutorialCenters() {
		return this.tutorialCenters;
	}

	public void setTutorialCenters(Set<TutorialCenter> tutorialCenters) {
		this.tutorialCenters = tutorialCenters;
	}

}
