package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentDetails generated by hbm2java
 */
@Entity
@Table(name = "student_details", catalog = "ptutors_db")
public class StudentDetails implements java.io.Serializable {

	private String studentId;
	private CountryName countryName;
	private EducationCategories educationCategoriesByTutionSegmentId;
	private EducationCategories educationCategoriesByEducationSegmentId;
	private LocationName locationName;
	private SchoolBoard schoolBoard;
	private SecretQuestion secretQuestion;
	private Subject subject;
	private TeachingMedium teachingMedium;
	private UniversityInstitute universityInstitute;
	private String name;
	private String userLoginName;
	private String password;
	private String secretQuestionAnswer;
	private String gender;
	private Integer age;
	private String area;
	private String landmark;
	private String postalCode;
	private String stateProvince;
	private String address;
	private String guardianName;
	private String contactNumber;
	private String emailAddress;
	private String callTime;
	private String otherSchoolBoard;
	private String otherUniversityInstituteName;
	private String otherEducationSegmentName;
	private String otherMediumName;
	private String tutionTitle;
	private String otherTutionRequiredSubjectName;
	private String otherTutionSegmentName;
	private String tutionRemarks;
	private Date registrationDate;
	private Boolean imageFlag;
	private Boolean profileVerificationStatus;
	private Boolean profileActiveDeactiveStatus;
	private String membershipCategory;
	private Integer duration;
	private String modeOfPayment;
	private Long paymentAmount;
	private String paymentId;
	private String transactionId;
	private Date paymentDate;
	private Date membershipBeginDate;
	private Date membershipExpireWarningDate;
	private Date membershipExpireDate;
	private Date registrationTime;

	public StudentDetails() {
	}

	public StudentDetails(String studentId) {
		this.studentId = studentId;
	}

	public StudentDetails(String studentId, CountryName countryName,
			EducationCategories educationCategoriesByTutionSegmentId,
			EducationCategories educationCategoriesByEducationSegmentId, LocationName locationName,
			SchoolBoard schoolBoard, SecretQuestion secretQuestion, Subject subject, TeachingMedium teachingMedium,
			UniversityInstitute universityInstitute, String name, String userLoginName, String password,
			String secretQuestionAnswer, String gender, Integer age, String area, String landmark, String postalCode,
			String stateProvince, String address, String guardianName, String contactNumber, String emailAddress,
			String callTime, String otherSchoolBoard, String otherUniversityInstituteName,
			String otherEducationSegmentName, String otherMediumName, String tutionTitle,
			String otherTutionRequiredSubjectName, String otherTutionSegmentName, String tutionRemarks,
			Date registrationDate, Boolean imageFlag, Boolean profileVerificationStatus,
			Boolean profileActiveDeactiveStatus, String membershipCategory, Integer duration, String modeOfPayment,
			Long paymentAmount, String paymentId, String transactionId, Date paymentDate, Date membershipBeginDate,
			Date membershipExpireWarningDate, Date membershipExpireDate, Date registrationTime) {
		this.studentId = studentId;
		this.countryName = countryName;
		this.educationCategoriesByTutionSegmentId = educationCategoriesByTutionSegmentId;
		this.educationCategoriesByEducationSegmentId = educationCategoriesByEducationSegmentId;
		this.locationName = locationName;
		this.schoolBoard = schoolBoard;
		this.secretQuestion = secretQuestion;
		this.subject = subject;
		this.teachingMedium = teachingMedium;
		this.universityInstitute = universityInstitute;
		this.name = name;
		this.userLoginName = userLoginName;
		this.password = password;
		this.secretQuestionAnswer = secretQuestionAnswer;
		this.gender = gender;
		this.age = age;
		this.area = area;
		this.landmark = landmark;
		this.postalCode = postalCode;
		this.stateProvince = stateProvince;
		this.address = address;
		this.guardianName = guardianName;
		this.contactNumber = contactNumber;
		this.emailAddress = emailAddress;
		this.callTime = callTime;
		this.otherSchoolBoard = otherSchoolBoard;
		this.otherUniversityInstituteName = otherUniversityInstituteName;
		this.otherEducationSegmentName = otherEducationSegmentName;
		this.otherMediumName = otherMediumName;
		this.tutionTitle = tutionTitle;
		this.otherTutionRequiredSubjectName = otherTutionRequiredSubjectName;
		this.otherTutionSegmentName = otherTutionSegmentName;
		this.tutionRemarks = tutionRemarks;
		this.registrationDate = registrationDate;
		this.imageFlag = imageFlag;
		this.profileVerificationStatus = profileVerificationStatus;
		this.profileActiveDeactiveStatus = profileActiveDeactiveStatus;
		this.membershipCategory = membershipCategory;
		this.duration = duration;
		this.modeOfPayment = modeOfPayment;
		this.paymentAmount = paymentAmount;
		this.paymentId = paymentId;
		this.transactionId = transactionId;
		this.paymentDate = paymentDate;
		this.membershipBeginDate = membershipBeginDate;
		this.membershipExpireWarningDate = membershipExpireWarningDate;
		this.membershipExpireDate = membershipExpireDate;
		this.registrationTime = registrationTime;
	}

	@Id

	@Column(name = "STUDENT_ID", unique = true, nullable = false, length = 10)
	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_CODE")
	public CountryName getCountryName() {
		return this.countryName;
	}

	public void setCountryName(CountryName countryName) {
		this.countryName = countryName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TUTION_SEGMENT_ID")
	public EducationCategories getEducationCategoriesByTutionSegmentId() {
		return this.educationCategoriesByTutionSegmentId;
	}

	public void setEducationCategoriesByTutionSegmentId(EducationCategories educationCategoriesByTutionSegmentId) {
		this.educationCategoriesByTutionSegmentId = educationCategoriesByTutionSegmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EDUCATION_SEGMENT_ID")
	public EducationCategories getEducationCategoriesByEducationSegmentId() {
		return this.educationCategoriesByEducationSegmentId;
	}

	public void setEducationCategoriesByEducationSegmentId(
			EducationCategories educationCategoriesByEducationSegmentId) {
		this.educationCategoriesByEducationSegmentId = educationCategoriesByEducationSegmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_ID")
	public LocationName getLocationName() {
		return this.locationName;
	}

	public void setLocationName(LocationName locationName) {
		this.locationName = locationName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHOOL_BOARD_ID")
	public SchoolBoard getSchoolBoard() {
		return this.schoolBoard;
	}

	public void setSchoolBoard(SchoolBoard schoolBoard) {
		this.schoolBoard = schoolBoard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECRET_QUESTION_ID")
	public SecretQuestion getSecretQuestion() {
		return this.secretQuestion;
	}

	public void setSecretQuestion(SecretQuestion secretQuestion) {
		this.secretQuestion = secretQuestion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TUTION_REQUIRED_SUBJECT_ID")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDIUM_ID")
	public TeachingMedium getTeachingMedium() {
		return this.teachingMedium;
	}

	public void setTeachingMedium(TeachingMedium teachingMedium) {
		this.teachingMedium = teachingMedium;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIVERSITY_INSTITUTE_ID")
	public UniversityInstitute getUniversityInstitute() {
		return this.universityInstitute;
	}

	public void setUniversityInstitute(UniversityInstitute universityInstitute) {
		this.universityInstitute = universityInstitute;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "USER_LOGIN_NAME", length = 200)
	public String getUserLoginName() {
		return this.userLoginName;
	}

	public void setUserLoginName(String userLoginName) {
		this.userLoginName = userLoginName;
	}

	@Column(name = "PASSWORD", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "SECRET_QUESTION_ANSWER", length = 200)
	public String getSecretQuestionAnswer() {
		return this.secretQuestionAnswer;
	}

	public void setSecretQuestionAnswer(String secretQuestionAnswer) {
		this.secretQuestionAnswer = secretQuestionAnswer;
	}

	@Column(name = "GENDER", length = 6)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "AGE")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "AREA", length = 200)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "LANDMARK", length = 200)
	public String getLandmark() {
		return this.landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	@Column(name = "POSTAL_CODE", length = 50)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "STATE_PROVINCE", length = 200)
	public String getStateProvince() {
		return this.stateProvince;
	}

	public void setStateProvince(String stateProvince) {
		this.stateProvince = stateProvince;
	}

	@Column(name = "ADDRESS", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "GUARDIAN_NAME", length = 100)
	public String getGuardianName() {
		return this.guardianName;
	}

	public void setGuardianName(String guardianName) {
		this.guardianName = guardianName;
	}

	@Column(name = "CONTACT_NUMBER", length = 200)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "EMAIL_ADDRESS", length = 200)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "CALL_TIME", length = 100)
	public String getCallTime() {
		return this.callTime;
	}

	public void setCallTime(String callTime) {
		this.callTime = callTime;
	}

	@Column(name = "OTHER_SCHOOL_BOARD", length = 200)
	public String getOtherSchoolBoard() {
		return this.otherSchoolBoard;
	}

	public void setOtherSchoolBoard(String otherSchoolBoard) {
		this.otherSchoolBoard = otherSchoolBoard;
	}

	@Column(name = "OTHER_UNIVERSITY_INSTITUTE_NAME", length = 200)
	public String getOtherUniversityInstituteName() {
		return this.otherUniversityInstituteName;
	}

	public void setOtherUniversityInstituteName(String otherUniversityInstituteName) {
		this.otherUniversityInstituteName = otherUniversityInstituteName;
	}

	@Column(name = "OTHER_EDUCATION_SEGMENT_NAME", length = 200)
	public String getOtherEducationSegmentName() {
		return this.otherEducationSegmentName;
	}

	public void setOtherEducationSegmentName(String otherEducationSegmentName) {
		this.otherEducationSegmentName = otherEducationSegmentName;
	}

	@Column(name = "OTHER_MEDIUM_NAME", length = 200)
	public String getOtherMediumName() {
		return this.otherMediumName;
	}

	public void setOtherMediumName(String otherMediumName) {
		this.otherMediumName = otherMediumName;
	}

	@Column(name = "TUTION_TITLE", length = 200)
	public String getTutionTitle() {
		return this.tutionTitle;
	}

	public void setTutionTitle(String tutionTitle) {
		this.tutionTitle = tutionTitle;
	}

	@Column(name = "OTHER_TUTION_REQUIRED_SUBJECT_NAME", length = 200)
	public String getOtherTutionRequiredSubjectName() {
		return this.otherTutionRequiredSubjectName;
	}

	public void setOtherTutionRequiredSubjectName(String otherTutionRequiredSubjectName) {
		this.otherTutionRequiredSubjectName = otherTutionRequiredSubjectName;
	}

	@Column(name = "OTHER_TUTION_SEGMENT_NAME", length = 200)
	public String getOtherTutionSegmentName() {
		return this.otherTutionSegmentName;
	}

	public void setOtherTutionSegmentName(String otherTutionSegmentName) {
		this.otherTutionSegmentName = otherTutionSegmentName;
	}

	@Column(name = "TUTION_REMARKS", length = 500)
	public String getTutionRemarks() {
		return this.tutionRemarks;
	}

	public void setTutionRemarks(String tutionRemarks) {
		this.tutionRemarks = tutionRemarks;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REGISTRATION_DATE", length = 10)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "IMAGE_FLAG")
	public Boolean getImageFlag() {
		return this.imageFlag;
	}

	public void setImageFlag(Boolean imageFlag) {
		this.imageFlag = imageFlag;
	}

	@Column(name = "PROFILE_VERIFICATION_STATUS")
	public Boolean getProfileVerificationStatus() {
		return this.profileVerificationStatus;
	}

	public void setProfileVerificationStatus(Boolean profileVerificationStatus) {
		this.profileVerificationStatus = profileVerificationStatus;
	}

	@Column(name = "PROFILE_ACTIVE_DEACTIVE_STATUS")
	public Boolean getProfileActiveDeactiveStatus() {
		return this.profileActiveDeactiveStatus;
	}

	public void setProfileActiveDeactiveStatus(Boolean profileActiveDeactiveStatus) {
		this.profileActiveDeactiveStatus = profileActiveDeactiveStatus;
	}

	@Column(name = "MEMBERSHIP_CATEGORY", length = 200)
	public String getMembershipCategory() {
		return this.membershipCategory;
	}

	public void setMembershipCategory(String membershipCategory) {
		this.membershipCategory = membershipCategory;
	}

	@Column(name = "DURATION")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "MODE_OF_PAYMENT", length = 200)
	public String getModeOfPayment() {
		return this.modeOfPayment;
	}

	public void setModeOfPayment(String modeOfPayment) {
		this.modeOfPayment = modeOfPayment;
	}

	@Column(name = "PAYMENT_AMOUNT", precision = 10, scale = 0)
	public Long getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(Long paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Column(name = "PAYMENT_ID", length = 20)
	public String getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "TRANSACTION_ID", length = 20)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAYMENT_DATE", length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_BEGIN_DATE", length = 10)
	public Date getMembershipBeginDate() {
		return this.membershipBeginDate;
	}

	public void setMembershipBeginDate(Date membershipBeginDate) {
		this.membershipBeginDate = membershipBeginDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_EXPIRE_WARNING_DATE", length = 10)
	public Date getMembershipExpireWarningDate() {
		return this.membershipExpireWarningDate;
	}

	public void setMembershipExpireWarningDate(Date membershipExpireWarningDate) {
		this.membershipExpireWarningDate = membershipExpireWarningDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_EXPIRE_DATE", length = 10)
	public Date getMembershipExpireDate() {
		return this.membershipExpireDate;
	}

	public void setMembershipExpireDate(Date membershipExpireDate) {
		this.membershipExpireDate = membershipExpireDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "REGISTRATION_TIME", length = 8)
	public Date getRegistrationTime() {
		return this.registrationTime;
	}

	public void setRegistrationTime(Date registrationTime) {
		this.registrationTime = registrationTime;
	}

}
