package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TeachingOption generated by hbm2java
 */
@Entity
@Table(name = "teaching_option", catalog = "ptutors_db")
public class TeachingOption implements java.io.Serializable {

	private Integer teachingOptionId;
	private String teachingOptionName;
	private Set<TutorTeachingOption> tutorTeachingOptions = new HashSet<TutorTeachingOption>(0);

	public TeachingOption() {
	}

	public TeachingOption(String teachingOptionName) {
		this.teachingOptionName = teachingOptionName;
	}

	public TeachingOption(String teachingOptionName, Set<TutorTeachingOption> tutorTeachingOptions) {
		this.teachingOptionName = teachingOptionName;
		this.tutorTeachingOptions = tutorTeachingOptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TEACHING_OPTION_ID", unique = true, nullable = false)
	public Integer getTeachingOptionId() {
		return this.teachingOptionId;
	}

	public void setTeachingOptionId(Integer teachingOptionId) {
		this.teachingOptionId = teachingOptionId;
	}

	@Column(name = "TEACHING_OPTION_NAME", nullable = false, length = 200)
	public String getTeachingOptionName() {
		return this.teachingOptionName;
	}

	public void setTeachingOptionName(String teachingOptionName) {
		this.teachingOptionName = teachingOptionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teachingOption")
	public Set<TutorTeachingOption> getTutorTeachingOptions() {
		return this.tutorTeachingOptions;
	}

	public void setTutorTeachingOptions(Set<TutorTeachingOption> tutorTeachingOptions) {
		this.tutorTeachingOptions = tutorTeachingOptions;
	}

}
