package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Teaser generated by hbm2java
 */
@Entity
@Table(name = "teaser", catalog = "ptutors_db")
public class Teaser implements java.io.Serializable {

	private Integer teaserId;
	private String teaserTitle;
	private String teaserSubjectLine1;
	private String teaserSubjectLine2;
	private String teaserSubjectLine3;
	private String teaserSubjectLine4;
	private String teaserSubjectLine5;

	public Teaser() {
	}

	public Teaser(String teaserTitle, String teaserSubjectLine1, String teaserSubjectLine2, String teaserSubjectLine3,
			String teaserSubjectLine4, String teaserSubjectLine5) {
		this.teaserTitle = teaserTitle;
		this.teaserSubjectLine1 = teaserSubjectLine1;
		this.teaserSubjectLine2 = teaserSubjectLine2;
		this.teaserSubjectLine3 = teaserSubjectLine3;
		this.teaserSubjectLine4 = teaserSubjectLine4;
		this.teaserSubjectLine5 = teaserSubjectLine5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "teaser_id", unique = true, nullable = false)
	public Integer getTeaserId() {
		return this.teaserId;
	}

	public void setTeaserId(Integer teaserId) {
		this.teaserId = teaserId;
	}

	@Column(name = "teaser_title", length = 50)
	public String getTeaserTitle() {
		return this.teaserTitle;
	}

	public void setTeaserTitle(String teaserTitle) {
		this.teaserTitle = teaserTitle;
	}

	@Column(name = "teaser_subject_line1", length = 100)
	public String getTeaserSubjectLine1() {
		return this.teaserSubjectLine1;
	}

	public void setTeaserSubjectLine1(String teaserSubjectLine1) {
		this.teaserSubjectLine1 = teaserSubjectLine1;
	}

	@Column(name = "teaser_subject_line2", length = 100)
	public String getTeaserSubjectLine2() {
		return this.teaserSubjectLine2;
	}

	public void setTeaserSubjectLine2(String teaserSubjectLine2) {
		this.teaserSubjectLine2 = teaserSubjectLine2;
	}

	@Column(name = "teaser_subject_line3", length = 100)
	public String getTeaserSubjectLine3() {
		return this.teaserSubjectLine3;
	}

	public void setTeaserSubjectLine3(String teaserSubjectLine3) {
		this.teaserSubjectLine3 = teaserSubjectLine3;
	}

	@Column(name = "teaser_subject_line4", length = 100)
	public String getTeaserSubjectLine4() {
		return this.teaserSubjectLine4;
	}

	public void setTeaserSubjectLine4(String teaserSubjectLine4) {
		this.teaserSubjectLine4 = teaserSubjectLine4;
	}

	@Column(name = "teaser_subject_line5", length = 100)
	public String getTeaserSubjectLine5() {
		return this.teaserSubjectLine5;
	}

	public void setTeaserSubjectLine5(String teaserSubjectLine5) {
		this.teaserSubjectLine5 = teaserSubjectLine5;
	}

}
