package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TutorTeachingSegmentId generated by hbm2java
 */
@Embeddable
public class TutorTeachingSegmentId implements java.io.Serializable {

	private String tutorId;
	private int educationSegmentId;
	private String otherTeachingSegmentName;

	public TutorTeachingSegmentId() {
	}

	public TutorTeachingSegmentId(String tutorId, int educationSegmentId) {
		this.tutorId = tutorId;
		this.educationSegmentId = educationSegmentId;
	}

	public TutorTeachingSegmentId(String tutorId, int educationSegmentId, String otherTeachingSegmentName) {
		this.tutorId = tutorId;
		this.educationSegmentId = educationSegmentId;
		this.otherTeachingSegmentName = otherTeachingSegmentName;
	}

	@Column(name = "TUTOR_ID", nullable = false, length = 10)
	public String getTutorId() {
		return this.tutorId;
	}

	public void setTutorId(String tutorId) {
		this.tutorId = tutorId;
	}

	@Column(name = "EDUCATION_SEGMENT_ID", nullable = false)
	public int getEducationSegmentId() {
		return this.educationSegmentId;
	}

	public void setEducationSegmentId(int educationSegmentId) {
		this.educationSegmentId = educationSegmentId;
	}

	@Column(name = "OTHER_TEACHING_SEGMENT_NAME", length = 200)
	public String getOtherTeachingSegmentName() {
		return this.otherTeachingSegmentName;
	}

	public void setOtherTeachingSegmentName(String otherTeachingSegmentName) {
		this.otherTeachingSegmentName = otherTeachingSegmentName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TutorTeachingSegmentId))
			return false;
		TutorTeachingSegmentId castOther = (TutorTeachingSegmentId) other;

		return ((this.getTutorId() == castOther.getTutorId()) || (this.getTutorId() != null
				&& castOther.getTutorId() != null && this.getTutorId().equals(castOther.getTutorId())))
				&& (this.getEducationSegmentId() == castOther.getEducationSegmentId())
				&& ((this.getOtherTeachingSegmentName() == castOther.getOtherTeachingSegmentName())
						|| (this.getOtherTeachingSegmentName() != null
								&& castOther.getOtherTeachingSegmentName() != null
								&& this.getOtherTeachingSegmentName().equals(castOther.getOtherTeachingSegmentName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTutorId() == null ? 0 : this.getTutorId().hashCode());
		result = 37 * result + this.getEducationSegmentId();
		result = 37 * result
				+ (getOtherTeachingSegmentName() == null ? 0 : this.getOtherTeachingSegmentName().hashCode());
		return result;
	}

}
