package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TutorDetails generated by hbm2java
 */
@Entity
@Table(name = "tutor_details", catalog = "ptutors_db")
public class TutorDetails implements java.io.Serializable {

	private String tutorId;
	private CountryName countryName;
	private LocationName locationName;
	private String name;
	private String userLoginName;
	private String password;
	private Integer secretQuestionId;
	private String secretQuestionAnswer;
	private Character gender;
	private Integer age;
	private String areaName;
	private String postalCode;
	private String stateProvince;
	private String address;
	private String contactNumber;
	private String emailAddress;
	private Integer yearsOfTutoringExperience;
	private String preferredTutoringArea;
	private String expectedFees;
	private String tutoringExperience;
	private Date registrationDate;
	private Byte imageFlag;
	private Boolean profileVerificationStatus;
	private Boolean profileActiveDeactiveStatus;
	private String membershipCategory;
	private Integer duration;
	private String modeOfPayment;
	private BigDecimal paymentAmount;
	private String paymentId;
	private String transactionId;
	private Date paymentDate;
	private Date membershipBeginDate;
	private Date membershipExpireWarningDate;
	private Date membershipExpireDate;
	private Boolean documentVerificationFlag;
	private Date registrationTime;
	private Set<TutorTeachingPatteren> tutorTeachingPatterens = new HashSet<TutorTeachingPatteren>(0);
	private Set<TutorTeachingOption> tutorTeachingOptions = new HashSet<TutorTeachingOption>(0);
	private Set<TutorUgEducation> tutorUgEducations = new HashSet<TutorUgEducation>(0);
	private Set<TutorMedium> tutorMediums = new HashSet<TutorMedium>(0);
	private Set<TutorPgEducation> tutorPgEducations = new HashSet<TutorPgEducation>(0);
	private Set<TutorTeachingSegment> tutorTeachingSegments = new HashSet<TutorTeachingSegment>(0);

	public TutorDetails() {
	}

	public TutorDetails(String tutorId) {
		this.tutorId = tutorId;
	}

	public TutorDetails(String tutorId, CountryName countryName, LocationName locationName, String name,
			String userLoginName, String password, Integer secretQuestionId, String secretQuestionAnswer,
			Character gender, Integer age, String areaName, String postalCode, String stateProvince, String address,
			String contactNumber, String emailAddress, Integer yearsOfTutoringExperience, String preferredTutoringArea,
			String expectedFees, String tutoringExperience, Date registrationDate, Byte imageFlag,
			Boolean profileVerificationStatus, Boolean profileActiveDeactiveStatus, String membershipCategory,
			Integer duration, String modeOfPayment, BigDecimal paymentAmount, String paymentId, String transactionId,
			Date paymentDate, Date membershipBeginDate, Date membershipExpireWarningDate, Date membershipExpireDate,
			Boolean documentVerificationFlag, Date registrationTime, Set<TutorTeachingPatteren> tutorTeachingPatterens,
			Set<TutorTeachingOption> tutorTeachingOptions, Set<TutorUgEducation> tutorUgEducations,
			Set<TutorMedium> tutorMediums, Set<TutorPgEducation> tutorPgEducations,
			Set<TutorTeachingSegment> tutorTeachingSegments) {
		this.tutorId = tutorId;
		this.countryName = countryName;
		this.locationName = locationName;
		this.name = name;
		this.userLoginName = userLoginName;
		this.password = password;
		this.secretQuestionId = secretQuestionId;
		this.secretQuestionAnswer = secretQuestionAnswer;
		this.gender = gender;
		this.age = age;
		this.areaName = areaName;
		this.postalCode = postalCode;
		this.stateProvince = stateProvince;
		this.address = address;
		this.contactNumber = contactNumber;
		this.emailAddress = emailAddress;
		this.yearsOfTutoringExperience = yearsOfTutoringExperience;
		this.preferredTutoringArea = preferredTutoringArea;
		this.expectedFees = expectedFees;
		this.tutoringExperience = tutoringExperience;
		this.registrationDate = registrationDate;
		this.imageFlag = imageFlag;
		this.profileVerificationStatus = profileVerificationStatus;
		this.profileActiveDeactiveStatus = profileActiveDeactiveStatus;
		this.membershipCategory = membershipCategory;
		this.duration = duration;
		this.modeOfPayment = modeOfPayment;
		this.paymentAmount = paymentAmount;
		this.paymentId = paymentId;
		this.transactionId = transactionId;
		this.paymentDate = paymentDate;
		this.membershipBeginDate = membershipBeginDate;
		this.membershipExpireWarningDate = membershipExpireWarningDate;
		this.membershipExpireDate = membershipExpireDate;
		this.documentVerificationFlag = documentVerificationFlag;
		this.registrationTime = registrationTime;
		this.tutorTeachingPatterens = tutorTeachingPatterens;
		this.tutorTeachingOptions = tutorTeachingOptions;
		this.tutorUgEducations = tutorUgEducations;
		this.tutorMediums = tutorMediums;
		this.tutorPgEducations = tutorPgEducations;
		this.tutorTeachingSegments = tutorTeachingSegments;
	}

	@Id

	@Column(name = "TUTOR_ID", unique = true, nullable = false, length = 10)
	public String getTutorId() {
		return this.tutorId;
	}

	public void setTutorId(String tutorId) {
		this.tutorId = tutorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_CODE")
	public CountryName getCountryName() {
		return this.countryName;
	}

	public void setCountryName(CountryName countryName) {
		this.countryName = countryName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_ID")
	public LocationName getLocationName() {
		return this.locationName;
	}

	public void setLocationName(LocationName locationName) {
		this.locationName = locationName;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "USER_LOGIN_NAME", length = 20)
	public String getUserLoginName() {
		return this.userLoginName;
	}

	public void setUserLoginName(String userLoginName) {
		this.userLoginName = userLoginName;
	}

	@Column(name = "PASSWORD", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "SECRET_QUESTION_ID")
	public Integer getSecretQuestionId() {
		return this.secretQuestionId;
	}

	public void setSecretQuestionId(Integer secretQuestionId) {
		this.secretQuestionId = secretQuestionId;
	}

	@Column(name = "SECRET_QUESTION_ANSWER", length = 200)
	public String getSecretQuestionAnswer() {
		return this.secretQuestionAnswer;
	}

	public void setSecretQuestionAnswer(String secretQuestionAnswer) {
		this.secretQuestionAnswer = secretQuestionAnswer;
	}

	@Column(name = "GENDER", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "AGE")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "AREA_NAME", length = 200)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "POSTAL_CODE", length = 50)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "STATE_PROVINCE", length = 200)
	public String getStateProvince() {
		return this.stateProvince;
	}

	public void setStateProvince(String stateProvince) {
		this.stateProvince = stateProvince;
	}

	@Column(name = "ADDRESS", length = 300)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CONTACT_NUMBER", length = 100)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "EMAIL_ADDRESS", length = 200)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "YEARS_OF_TUTORING_EXPERIENCE")
	public Integer getYearsOfTutoringExperience() {
		return this.yearsOfTutoringExperience;
	}

	public void setYearsOfTutoringExperience(Integer yearsOfTutoringExperience) {
		this.yearsOfTutoringExperience = yearsOfTutoringExperience;
	}

	@Column(name = "PREFERRED_TUTORING_AREA", length = 200)
	public String getPreferredTutoringArea() {
		return this.preferredTutoringArea;
	}

	public void setPreferredTutoringArea(String preferredTutoringArea) {
		this.preferredTutoringArea = preferredTutoringArea;
	}

	@Column(name = "EXPECTED_FEES", length = 100)
	public String getExpectedFees() {
		return this.expectedFees;
	}

	public void setExpectedFees(String expectedFees) {
		this.expectedFees = expectedFees;
	}

	@Column(name = "TUTORING_EXPERIENCE", length = 500)
	public String getTutoringExperience() {
		return this.tutoringExperience;
	}

	public void setTutoringExperience(String tutoringExperience) {
		this.tutoringExperience = tutoringExperience;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REGISTRATION_DATE", length = 10)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "IMAGE_FLAG")
	public Byte getImageFlag() {
		return this.imageFlag;
	}

	public void setImageFlag(Byte imageFlag) {
		this.imageFlag = imageFlag;
	}

	@Column(name = "PROFILE_VERIFICATION_STATUS")
	public Boolean getProfileVerificationStatus() {
		return this.profileVerificationStatus;
	}

	public void setProfileVerificationStatus(Boolean profileVerificationStatus) {
		this.profileVerificationStatus = profileVerificationStatus;
	}

	@Column(name = "PROFILE_ACTIVE_DEACTIVE_STATUS")
	public Boolean getProfileActiveDeactiveStatus() {
		return this.profileActiveDeactiveStatus;
	}

	public void setProfileActiveDeactiveStatus(Boolean profileActiveDeactiveStatus) {
		this.profileActiveDeactiveStatus = profileActiveDeactiveStatus;
	}

	@Column(name = "MEMBERSHIP_CATEGORY", length = 100)
	public String getMembershipCategory() {
		return this.membershipCategory;
	}

	public void setMembershipCategory(String membershipCategory) {
		this.membershipCategory = membershipCategory;
	}

	@Column(name = "DURATION")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "MODE_OF_PAYMENT", length = 200)
	public String getModeOfPayment() {
		return this.modeOfPayment;
	}

	public void setModeOfPayment(String modeOfPayment) {
		this.modeOfPayment = modeOfPayment;
	}

	@Column(name = "PAYMENT_AMOUNT", precision = 10)
	public BigDecimal getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(BigDecimal paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Column(name = "PAYMENT_ID", length = 20)
	public String getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "TRANSACTION_ID", length = 20)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAYMENT_DATE", length = 10)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_BEGIN_DATE", length = 10)
	public Date getMembershipBeginDate() {
		return this.membershipBeginDate;
	}

	public void setMembershipBeginDate(Date membershipBeginDate) {
		this.membershipBeginDate = membershipBeginDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_EXPIRE_WARNING_DATE", length = 10)
	public Date getMembershipExpireWarningDate() {
		return this.membershipExpireWarningDate;
	}

	public void setMembershipExpireWarningDate(Date membershipExpireWarningDate) {
		this.membershipExpireWarningDate = membershipExpireWarningDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_EXPIRE_DATE", length = 10)
	public Date getMembershipExpireDate() {
		return this.membershipExpireDate;
	}

	public void setMembershipExpireDate(Date membershipExpireDate) {
		this.membershipExpireDate = membershipExpireDate;
	}

	@Column(name = "DOCUMENT_VERIFICATION_FLAG")
	public Boolean getDocumentVerificationFlag() {
		return this.documentVerificationFlag;
	}

	public void setDocumentVerificationFlag(Boolean documentVerificationFlag) {
		this.documentVerificationFlag = documentVerificationFlag;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "REGISTRATION_TIME", length = 8)
	public Date getRegistrationTime() {
		return this.registrationTime;
	}

	public void setRegistrationTime(Date registrationTime) {
		this.registrationTime = registrationTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tutorDetails")
	public Set<TutorTeachingPatteren> getTutorTeachingPatterens() {
		return this.tutorTeachingPatterens;
	}

	public void setTutorTeachingPatterens(Set<TutorTeachingPatteren> tutorTeachingPatterens) {
		this.tutorTeachingPatterens = tutorTeachingPatterens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tutorDetails")
	public Set<TutorTeachingOption> getTutorTeachingOptions() {
		return this.tutorTeachingOptions;
	}

	public void setTutorTeachingOptions(Set<TutorTeachingOption> tutorTeachingOptions) {
		this.tutorTeachingOptions = tutorTeachingOptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tutorDetails")
	public Set<TutorUgEducation> getTutorUgEducations() {
		return this.tutorUgEducations;
	}

	public void setTutorUgEducations(Set<TutorUgEducation> tutorUgEducations) {
		this.tutorUgEducations = tutorUgEducations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tutorDetails")
	public Set<TutorMedium> getTutorMediums() {
		return this.tutorMediums;
	}

	public void setTutorMediums(Set<TutorMedium> tutorMediums) {
		this.tutorMediums = tutorMediums;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tutorDetails")
	public Set<TutorPgEducation> getTutorPgEducations() {
		return this.tutorPgEducations;
	}

	public void setTutorPgEducations(Set<TutorPgEducation> tutorPgEducations) {
		this.tutorPgEducations = tutorPgEducations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tutorDetails")
	public Set<TutorTeachingSegment> getTutorTeachingSegments() {
		return this.tutorTeachingSegments;
	}

	public void setTutorTeachingSegments(Set<TutorTeachingSegment> tutorTeachingSegments) {
		this.tutorTeachingSegments = tutorTeachingSegments;
	}

}
