package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TutorTeachingSegment generated by hbm2java
 */
@Entity
@Table(name = "tutor_teaching_segment", catalog = "ptutors_db")
public class TutorTeachingSegment implements java.io.Serializable {

	private TutorTeachingSegmentId id;
	private EducationCategories educationCategories;
	private TutorDetails tutorDetails;

	public TutorTeachingSegment() {
	}

	public TutorTeachingSegment(TutorTeachingSegmentId id, EducationCategories educationCategories,
			TutorDetails tutorDetails) {
		this.id = id;
		this.educationCategories = educationCategories;
		this.tutorDetails = tutorDetails;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tutorId", column = @Column(name = "TUTOR_ID", nullable = false, length = 10)),
			@AttributeOverride(name = "educationSegmentId", column = @Column(name = "EDUCATION_SEGMENT_ID", nullable = false)),
			@AttributeOverride(name = "otherTeachingSegmentName", column = @Column(name = "OTHER_TEACHING_SEGMENT_NAME", length = 200)) })
	public TutorTeachingSegmentId getId() {
		return this.id;
	}

	public void setId(TutorTeachingSegmentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EDUCATION_SEGMENT_ID", nullable = false, insertable = false, updatable = false)
	public EducationCategories getEducationCategories() {
		return this.educationCategories;
	}

	public void setEducationCategories(EducationCategories educationCategories) {
		this.educationCategories = educationCategories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TUTOR_ID", nullable = false, insertable = false, updatable = false)
	public TutorDetails getTutorDetails() {
		return this.tutorDetails;
	}

	public void setTutorDetails(TutorDetails tutorDetails) {
		this.tutorDetails = tutorDetails;
	}

}
