package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TutorTeachingOptionId generated by hbm2java
 */
@Embeddable
public class TutorTeachingOptionId implements java.io.Serializable {

	private String tutorId;
	private int teachingOptionId;
	private String otherTeachingOptionName;

	public TutorTeachingOptionId() {
	}

	public TutorTeachingOptionId(String tutorId, int teachingOptionId) {
		this.tutorId = tutorId;
		this.teachingOptionId = teachingOptionId;
	}

	public TutorTeachingOptionId(String tutorId, int teachingOptionId, String otherTeachingOptionName) {
		this.tutorId = tutorId;
		this.teachingOptionId = teachingOptionId;
		this.otherTeachingOptionName = otherTeachingOptionName;
	}

	@Column(name = "TUTOR_ID", nullable = false, length = 10)
	public String getTutorId() {
		return this.tutorId;
	}

	public void setTutorId(String tutorId) {
		this.tutorId = tutorId;
	}

	@Column(name = "TEACHING_OPTION_ID", nullable = false)
	public int getTeachingOptionId() {
		return this.teachingOptionId;
	}

	public void setTeachingOptionId(int teachingOptionId) {
		this.teachingOptionId = teachingOptionId;
	}

	@Column(name = "OTHER_TEACHING_OPTION_NAME", length = 200)
	public String getOtherTeachingOptionName() {
		return this.otherTeachingOptionName;
	}

	public void setOtherTeachingOptionName(String otherTeachingOptionName) {
		this.otherTeachingOptionName = otherTeachingOptionName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TutorTeachingOptionId))
			return false;
		TutorTeachingOptionId castOther = (TutorTeachingOptionId) other;

		return ((this.getTutorId() == castOther.getTutorId()) || (this.getTutorId() != null
				&& castOther.getTutorId() != null && this.getTutorId().equals(castOther.getTutorId())))
				&& (this.getTeachingOptionId() == castOther.getTeachingOptionId())
				&& ((this.getOtherTeachingOptionName() == castOther.getOtherTeachingOptionName())
						|| (this.getOtherTeachingOptionName() != null && castOther.getOtherTeachingOptionName() != null
								&& this.getOtherTeachingOptionName().equals(castOther.getOtherTeachingOptionName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTutorId() == null ? 0 : this.getTutorId().hashCode());
		result = 37 * result + this.getTeachingOptionId();
		result = 37 * result
				+ (getOtherTeachingOptionName() == null ? 0 : this.getOtherTeachingOptionName().hashCode());
		return result;
	}

}
