package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TutorMembershipSubscriptionId generated by hbm2java
 */
@Embeddable
public class TutorMembershipSubscriptionId implements java.io.Serializable {

	private String userId;
	private String userLoginName;
	private String userPassword;

	public TutorMembershipSubscriptionId() {
	}

	public TutorMembershipSubscriptionId(String userId, String userLoginName, String userPassword) {
		this.userId = userId;
		this.userLoginName = userLoginName;
		this.userPassword = userPassword;
	}

	@Column(name = "USER_ID", nullable = false, length = 6)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_LOGIN_NAME", nullable = false, length = 200)
	public String getUserLoginName() {
		return this.userLoginName;
	}

	public void setUserLoginName(String userLoginName) {
		this.userLoginName = userLoginName;
	}

	@Column(name = "USER_PASSWORD", nullable = false, length = 20)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TutorMembershipSubscriptionId))
			return false;
		TutorMembershipSubscriptionId castOther = (TutorMembershipSubscriptionId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserLoginName() == castOther.getUserLoginName())
						|| (this.getUserLoginName() != null && castOther.getUserLoginName() != null
								&& this.getUserLoginName().equals(castOther.getUserLoginName())))
				&& ((this.getUserPassword() == castOther.getUserPassword())
						|| (this.getUserPassword() != null && castOther.getUserPassword() != null
								&& this.getUserPassword().equals(castOther.getUserPassword())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getUserLoginName() == null ? 0 : this.getUserLoginName().hashCode());
		result = 37 * result + (getUserPassword() == null ? 0 : this.getUserPassword().hashCode());
		return result;
	}

}
