package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TutorSubject generated by hbm2java
 */
@Entity
@Table(name = "tutor_subject", catalog = "ptutors_db")
public class TutorSubject implements java.io.Serializable {

	private TutorSubjectId id;

	public TutorSubject() {
	}

	public TutorSubject(TutorSubjectId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tutorId", column = @Column(name = "TUTOR_ID", nullable = false, length = 10)),
			@AttributeOverride(name = "subjectId", column = @Column(name = "SUBJECT_ID", nullable = false)),
			@AttributeOverride(name = "otherSubjectName", column = @Column(name = "OTHER_SUBJECT_NAME", length = 200)) })
	public TutorSubjectId getId() {
		return this.id;
	}

	public void setId(TutorSubjectId id) {
		this.id = id;
	}

}
