package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TutorMedium generated by hbm2java
 */
@Entity
@Table(name = "tutor_medium", catalog = "ptutors_db")
public class TutorMedium implements java.io.Serializable {

	private TutorMediumId id;
	private TeachingMedium teachingMedium;
	private TutorDetails tutorDetails;

	public TutorMedium() {
	}

	public TutorMedium(TutorMediumId id, TeachingMedium teachingMedium, TutorDetails tutorDetails) {
		this.id = id;
		this.teachingMedium = teachingMedium;
		this.tutorDetails = tutorDetails;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tutorId", column = @Column(name = "TUTOR_ID", nullable = false, length = 10)),
			@AttributeOverride(name = "mediumId", column = @Column(name = "MEDIUM_ID", nullable = false)),
			@AttributeOverride(name = "otherMediumName", column = @Column(name = "OTHER_MEDIUM_NAME", length = 200)) })
	public TutorMediumId getId() {
		return this.id;
	}

	public void setId(TutorMediumId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDIUM_ID", nullable = false, insertable = false, updatable = false)
	public TeachingMedium getTeachingMedium() {
		return this.teachingMedium;
	}

	public void setTeachingMedium(TeachingMedium teachingMedium) {
		this.teachingMedium = teachingMedium;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TUTOR_ID", nullable = false, insertable = false, updatable = false)
	public TutorDetails getTutorDetails() {
		return this.tutorDetails;
	}

	public void setTutorDetails(TutorDetails tutorDetails) {
		this.tutorDetails = tutorDetails;
	}

}
