package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TutorPgEducationId generated by hbm2java
 */
@Embeddable
public class TutorPgEducationId implements java.io.Serializable {

	private String tutorId;
	private Integer courseId;
	private String otherCourseName;
	private Integer subjectId;
	private String otherSubjectName;
	private Integer universityInstituteId;
	private String otherUniversityInstituteName;
	private Integer yearOfPassout;
	private String resultStandard;

	public TutorPgEducationId() {
	}

	public TutorPgEducationId(String tutorId) {
		this.tutorId = tutorId;
	}

	public TutorPgEducationId(String tutorId, Integer courseId, String otherCourseName, Integer subjectId,
			String otherSubjectName, Integer universityInstituteId, String otherUniversityInstituteName,
			Integer yearOfPassout, String resultStandard) {
		this.tutorId = tutorId;
		this.courseId = courseId;
		this.otherCourseName = otherCourseName;
		this.subjectId = subjectId;
		this.otherSubjectName = otherSubjectName;
		this.universityInstituteId = universityInstituteId;
		this.otherUniversityInstituteName = otherUniversityInstituteName;
		this.yearOfPassout = yearOfPassout;
		this.resultStandard = resultStandard;
	}

	@Column(name = "tutor_id", nullable = false, length = 10)
	public String getTutorId() {
		return this.tutorId;
	}

	public void setTutorId(String tutorId) {
		this.tutorId = tutorId;
	}

	@Column(name = "course_id")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "other_course_name", length = 200)
	public String getOtherCourseName() {
		return this.otherCourseName;
	}

	public void setOtherCourseName(String otherCourseName) {
		this.otherCourseName = otherCourseName;
	}

	@Column(name = "subject_id")
	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "other_subject_name", length = 200)
	public String getOtherSubjectName() {
		return this.otherSubjectName;
	}

	public void setOtherSubjectName(String otherSubjectName) {
		this.otherSubjectName = otherSubjectName;
	}

	@Column(name = "university_institute_id")
	public Integer getUniversityInstituteId() {
		return this.universityInstituteId;
	}

	public void setUniversityInstituteId(Integer universityInstituteId) {
		this.universityInstituteId = universityInstituteId;
	}

	@Column(name = "other_university_institute_name", length = 200)
	public String getOtherUniversityInstituteName() {
		return this.otherUniversityInstituteName;
	}

	public void setOtherUniversityInstituteName(String otherUniversityInstituteName) {
		this.otherUniversityInstituteName = otherUniversityInstituteName;
	}

	@Column(name = "year_of_passout")
	public Integer getYearOfPassout() {
		return this.yearOfPassout;
	}

	public void setYearOfPassout(Integer yearOfPassout) {
		this.yearOfPassout = yearOfPassout;
	}

	@Column(name = "result_standard", length = 50)
	public String getResultStandard() {
		return this.resultStandard;
	}

	public void setResultStandard(String resultStandard) {
		this.resultStandard = resultStandard;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TutorPgEducationId))
			return false;
		TutorPgEducationId castOther = (TutorPgEducationId) other;

		return ((this.getTutorId() == castOther.getTutorId()) || (this.getTutorId() != null
				&& castOther.getTutorId() != null && this.getTutorId().equals(castOther.getTutorId())))
				&& ((this.getCourseId() == castOther.getCourseId()) || (this.getCourseId() != null
						&& castOther.getCourseId() != null && this.getCourseId().equals(castOther.getCourseId())))
				&& ((this.getOtherCourseName() == castOther.getOtherCourseName())
						|| (this.getOtherCourseName() != null && castOther.getOtherCourseName() != null
								&& this.getOtherCourseName().equals(castOther.getOtherCourseName())))
				&& ((this.getSubjectId() == castOther.getSubjectId()) || (this.getSubjectId() != null
						&& castOther.getSubjectId() != null && this.getSubjectId().equals(castOther.getSubjectId())))
				&& ((this.getOtherSubjectName() == castOther.getOtherSubjectName())
						|| (this.getOtherSubjectName() != null && castOther.getOtherSubjectName() != null
								&& this.getOtherSubjectName().equals(castOther.getOtherSubjectName())))
				&& ((this.getUniversityInstituteId() == castOther.getUniversityInstituteId())
						|| (this.getUniversityInstituteId() != null && castOther.getUniversityInstituteId() != null
								&& this.getUniversityInstituteId().equals(castOther.getUniversityInstituteId())))
				&& ((this.getOtherUniversityInstituteName() == castOther.getOtherUniversityInstituteName())
						|| (this.getOtherUniversityInstituteName() != null
								&& castOther.getOtherUniversityInstituteName() != null
								&& this.getOtherUniversityInstituteName()
										.equals(castOther.getOtherUniversityInstituteName())))
				&& ((this.getYearOfPassout() == castOther.getYearOfPassout())
						|| (this.getYearOfPassout() != null && castOther.getYearOfPassout() != null
								&& this.getYearOfPassout().equals(castOther.getYearOfPassout())))
				&& ((this.getResultStandard() == castOther.getResultStandard())
						|| (this.getResultStandard() != null && castOther.getResultStandard() != null
								&& this.getResultStandard().equals(castOther.getResultStandard())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTutorId() == null ? 0 : this.getTutorId().hashCode());
		result = 37 * result + (getCourseId() == null ? 0 : this.getCourseId().hashCode());
		result = 37 * result + (getOtherCourseName() == null ? 0 : this.getOtherCourseName().hashCode());
		result = 37 * result + (getSubjectId() == null ? 0 : this.getSubjectId().hashCode());
		result = 37 * result + (getOtherSubjectName() == null ? 0 : this.getOtherSubjectName().hashCode());
		result = 37 * result + (getUniversityInstituteId() == null ? 0 : this.getUniversityInstituteId().hashCode());
		result = 37 * result
				+ (getOtherUniversityInstituteName() == null ? 0 : this.getOtherUniversityInstituteName().hashCode());
		result = 37 * result + (getYearOfPassout() == null ? 0 : this.getYearOfPassout().hashCode());
		result = 37 * result + (getResultStandard() == null ? 0 : this.getResultStandard().hashCode());
		return result;
	}

}
