package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TutorTeachingArena generated by hbm2java
 */
@Entity
@Table(name = "tutor_teaching_arena", catalog = "ptutors_db")
public class TutorTeachingArena implements java.io.Serializable {

	private Integer tutorTeachingArenaId;
	private String tutorId;
	private Integer educationSegmentId;
	private String tutorTeachingSubjects;
	private String tutorTeachingBoard;
	private String tutorTeachingMedium;

	public TutorTeachingArena() {
	}

	public TutorTeachingArena(String tutorId) {
		this.tutorId = tutorId;
	}

	public TutorTeachingArena(String tutorId, Integer educationSegmentId, String tutorTeachingSubjects,
			String tutorTeachingBoard, String tutorTeachingMedium) {
		this.tutorId = tutorId;
		this.educationSegmentId = educationSegmentId;
		this.tutorTeachingSubjects = tutorTeachingSubjects;
		this.tutorTeachingBoard = tutorTeachingBoard;
		this.tutorTeachingMedium = tutorTeachingMedium;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tutor_teaching_arena_id", unique = true, nullable = false)
	public Integer getTutorTeachingArenaId() {
		return this.tutorTeachingArenaId;
	}

	public void setTutorTeachingArenaId(Integer tutorTeachingArenaId) {
		this.tutorTeachingArenaId = tutorTeachingArenaId;
	}

	@Column(name = "tutor_id", nullable = false, length = 10)
	public String getTutorId() {
		return this.tutorId;
	}

	public void setTutorId(String tutorId) {
		this.tutorId = tutorId;
	}

	@Column(name = "education_segment_id")
	public Integer getEducationSegmentId() {
		return this.educationSegmentId;
	}

	public void setEducationSegmentId(Integer educationSegmentId) {
		this.educationSegmentId = educationSegmentId;
	}

	@Column(name = "tutor_teaching_subjects", length = 500)
	public String getTutorTeachingSubjects() {
		return this.tutorTeachingSubjects;
	}

	public void setTutorTeachingSubjects(String tutorTeachingSubjects) {
		this.tutorTeachingSubjects = tutorTeachingSubjects;
	}

	@Column(name = "tutor_teaching_board", length = 300)
	public String getTutorTeachingBoard() {
		return this.tutorTeachingBoard;
	}

	public void setTutorTeachingBoard(String tutorTeachingBoard) {
		this.tutorTeachingBoard = tutorTeachingBoard;
	}

	@Column(name = "tutor_teaching_medium", length = 300)
	public String getTutorTeachingMedium() {
		return this.tutorTeachingMedium;
	}

	public void setTutorTeachingMedium(String tutorTeachingMedium) {
		this.tutorTeachingMedium = tutorTeachingMedium;
	}

}
