package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TutorMembershipSubscription generated by hbm2java
 */
@Entity
@Table(name = "tutor_membership_subscription", catalog = "ptutors_db")
public class TutorMembershipSubscription implements java.io.Serializable {

	private TutorMembershipSubscriptionId id;
	private String membershipCategory;
	private String duration;
	private BigDecimal paymentAmount;
	private Date membershipBeginDate;
	private Date membershipExpireDate;

	public TutorMembershipSubscription() {
	}

	public TutorMembershipSubscription(TutorMembershipSubscriptionId id, String membershipCategory) {
		this.id = id;
		this.membershipCategory = membershipCategory;
	}

	public TutorMembershipSubscription(TutorMembershipSubscriptionId id, String membershipCategory, String duration,
			BigDecimal paymentAmount, Date membershipBeginDate, Date membershipExpireDate) {
		this.id = id;
		this.membershipCategory = membershipCategory;
		this.duration = duration;
		this.paymentAmount = paymentAmount;
		this.membershipBeginDate = membershipBeginDate;
		this.membershipExpireDate = membershipExpireDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 6)),
			@AttributeOverride(name = "userLoginName", column = @Column(name = "USER_LOGIN_NAME", nullable = false, length = 200)),
			@AttributeOverride(name = "userPassword", column = @Column(name = "USER_PASSWORD", nullable = false, length = 20)) })
	public TutorMembershipSubscriptionId getId() {
		return this.id;
	}

	public void setId(TutorMembershipSubscriptionId id) {
		this.id = id;
	}

	@Column(name = "MEMBERSHIP_CATEGORY", nullable = false, length = 100)
	public String getMembershipCategory() {
		return this.membershipCategory;
	}

	public void setMembershipCategory(String membershipCategory) {
		this.membershipCategory = membershipCategory;
	}

	@Column(name = "DURATION", length = 100)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "PAYMENT_AMOUNT", precision = 10)
	public BigDecimal getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(BigDecimal paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_BEGIN_DATE", length = 10)
	public Date getMembershipBeginDate() {
		return this.membershipBeginDate;
	}

	public void setMembershipBeginDate(Date membershipBeginDate) {
		this.membershipBeginDate = membershipBeginDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MEMBERSHIP_EXPIRE_DATE", length = 10)
	public Date getMembershipExpireDate() {
		return this.membershipExpireDate;
	}

	public void setMembershipExpireDate(Date membershipExpireDate) {
		this.membershipExpireDate = membershipExpireDate;
	}

}
