package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UniversityInstitute generated by hbm2java
 */
@Entity
@Table(name = "university_institute", catalog = "ptutors_db")
public class UniversityInstitute implements java.io.Serializable {

	private Integer universityInstituteId;
	private CountryName countryName;
	private LocationName locationName;
	private String universityInstituteName;
	private Set<TutorPgEducation> tutorPgEducations = new HashSet<TutorPgEducation>(0);
	private Set<TutorUgEducation> tutorUgEducations = new HashSet<TutorUgEducation>(0);
	private Set<StudentDetails> studentDetailses = new HashSet<StudentDetails>(0);

	public UniversityInstitute() {
	}

	public UniversityInstitute(CountryName countryName, LocationName locationName, String universityInstituteName,
			Set<TutorPgEducation> tutorPgEducations, Set<TutorUgEducation> tutorUgEducations,
			Set<StudentDetails> studentDetailses) {
		this.countryName = countryName;
		this.locationName = locationName;
		this.universityInstituteName = universityInstituteName;
		this.tutorPgEducations = tutorPgEducations;
		this.tutorUgEducations = tutorUgEducations;
		this.studentDetailses = studentDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UNIVERSITY_INSTITUTE_ID", unique = true, nullable = false)
	public Integer getUniversityInstituteId() {
		return this.universityInstituteId;
	}

	public void setUniversityInstituteId(Integer universityInstituteId) {
		this.universityInstituteId = universityInstituteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_CODE")
	public CountryName getCountryName() {
		return this.countryName;
	}

	public void setCountryName(CountryName countryName) {
		this.countryName = countryName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_ID")
	public LocationName getLocationName() {
		return this.locationName;
	}

	public void setLocationName(LocationName locationName) {
		this.locationName = locationName;
	}

	@Column(name = "UNIVERSITY_INSTITUTE_NAME", length = 300)
	public String getUniversityInstituteName() {
		return this.universityInstituteName;
	}

	public void setUniversityInstituteName(String universityInstituteName) {
		this.universityInstituteName = universityInstituteName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "universityInstitute")
	public Set<TutorPgEducation> getTutorPgEducations() {
		return this.tutorPgEducations;
	}

	public void setTutorPgEducations(Set<TutorPgEducation> tutorPgEducations) {
		this.tutorPgEducations = tutorPgEducations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "universityInstitute")
	public Set<TutorUgEducation> getTutorUgEducations() {
		return this.tutorUgEducations;
	}

	public void setTutorUgEducations(Set<TutorUgEducation> tutorUgEducations) {
		this.tutorUgEducations = tutorUgEducations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "universityInstitute")
	public Set<StudentDetails> getStudentDetailses() {
		return this.studentDetailses;
	}

	public void setStudentDetailses(Set<StudentDetails> studentDetailses) {
		this.studentDetailses = studentDetailses;
	}

}
