package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserProfiles generated by hbm2java
 */
@Entity
@Table(name = "user_profiles", catalog = "ptutors_db")
public class UserProfiles implements java.io.Serializable {

	private UserProfilesId id;

	public UserProfiles() {
	}

	public UserProfiles(UserProfilesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 20)),
			@AttributeOverride(name = "password", column = @Column(name = "password", nullable = false, length = 20)),
			@AttributeOverride(name = "userRole", column = @Column(name = "user_role", nullable = false, length = 20)) })
	public UserProfilesId getId() {
		return this.id;
	}

	public void setId(UserProfilesId id) {
		this.id = id;
	}

}
