package com.pcs.pojo;
// Generated 5 Sep, 2018 6:08:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ViewCount generated by hbm2java
 */
@Entity
@Table(name = "view_count", catalog = "ptutors_db")
public class ViewCount implements java.io.Serializable {

	private int viewCounter;

	public ViewCount() {
	}

	public ViewCount(int viewCounter) {
		this.viewCounter = viewCounter;
	}

	@Id

	@Column(name = "view_counter", unique = true, nullable = false)
	public int getViewCounter() {
		return this.viewCounter;
	}

	public void setViewCounter(int viewCounter) {
		this.viewCounter = viewCounter;
	}

}
